### ISSUE TITLE
upload file failed

### ISSUE THREAD

**Issue by ChiLynn123** [doccano/doccano#1005]
Hello, I made an error uploading the document using the API, but the document can appear in the Doccano instance database. Looking forward to your reply to my questions, thank you very much!

r_du = doccano_client.post_doc_upload(8, "json", "fail1.json", "D:\WPSCloud")

error:
Traceback (most recent call last): File "D:/doccano/doccano-client/doccano_api_client/example.py", line 113, in <module> r_du = doccano_client.post_doc_upload(8, "csv", "data_xa.csv", "D:\WPSCloud") File "D:\doccano\doccano-client\doccano_api_client\__init__.py", line 521, in post_doc_upload data=data File "D:\doccano\doccano-client\doccano_api_client\__init__.py", line 64, in post request_url, data=data, files=files, json=json).json() File "E:\Anaconda\lib\site-packages\requests\models.py", line 885, in json return complexjson.loads(self.text, **kwargs) File "E:\Anaconda\lib\json\__init__.py", line 354, in loads return _default_decoder.decode(s) File "E:\Anaconda\lib\json\decoder.py", line 339, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "E:\Anaconda\lib\json\decoder.py", line 357, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Hironsan** [comment]
Please paste an example of your file.

**Comment by ChiLynn123** [comment]
I can't upload a file in JSON format, Please try converting this file to JSON format.thanks very much!
[example.txt](https://github.com/doccano/doccano/files/5290647/example.txt)

**Comment by ChiLynn123** [comment]
I used CSV or JSON modules to generate standard CSV and JSON document invocation API interface, which also failed to upload.But this data can be seen in a database on the Web side.

**Comment by MaxHoefl** [comment]
Same issue here: The doccano client [returns](https://github.com/doccano/doccano-client/blob/c0f5c13eee1751bf801338e8dc2258ed6d22fb3a/doccano_api_client/__init__.py#L61)
```
return self.session.post(
                request_url, data=data, files=files, json=json).json()
```

when `POST`ing a new document to `/v1/projects/<id>/docs`. 
The document is created correctly (`201`) but the `.json()` throws a `JSONDecodeError` as the content of the returned json is empty, i.e. it simply cannot parse anything.

@Hironsan should the API return a content from the post request `/v1/projects/<id>/docs` ? Or should this be fixed in the doccano client ?
