### ISSUE TITLE
Container not starting or created while using command docker-compose -f docker-compose.dev.yml up

### ISSUE THREAD

**Issue by strivedi02** [doccano/doccano#1022]
Error message
---------
```
(venv) Shubham:~/Shubham/Projects/doccano$ docker-compose -f docker-compose.dev.yml up
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 403, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 205, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 228, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 188, in __init__
  File "docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[28410] Failed to execute script docker-compose
```

My Environment
---------
*   Operating System: Ubuntu 18.04 LTS
*   Python Version Used: 3.6
*   While running the command: docker-compose -f docker-compose.dev.yml up
*  I followed all the procedures mentioned in the readme.

**Comment by PATELS2R** [comment]
Seems like it doesn't have enough privileges. Try the command using sudo
`sudo docker-compose -f docker-compose.dev.yml up`

**Comment by MASA49** [comment]
Hello I get this message 
xxxx@xxxx-Lenovo-Yoga-2-13:~$ sudo docker-compose -f docker-compose.dev.yml up
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose.dev.yml'

I think it is not correctly installed?

**Comment by MASA49** [comment]
I had solved my probleme 

blabla@blabla-Lenovo-Yoga-2-13:~/myprojectk$ sudo docker-compose -f docker-compose.yaml up
