### ISSUE TITLE
web page response slow

### ISSUE THREAD

**Issue by Nipi64310** [doccano/doccano#1056]
python and docker run method  both response very slow. 
Response time is about 10+s, it takes a long time to click any button.

chrome version latest & used in china

**Comment by icoxfog417** [comment]
Please provide your environment information following the [ISSUE_TEMPLATE](https://github.com/doccano/doccano/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by Nipi64310** [comment]
> Please provide your environment information following the [ISSUE_TEMPLATE](https://github.com/doccano/doccano/blob/master/.github/ISSUE_TEMPLATE.md).

System information
OS Platform and Distribution
```
uname -mrs
Linux 3.10.0-957.21.3.el7.x86_64 x86_64
```

Python version:  Python 3.7.6  host ip
Describe the problem:
python and docker run method both response very slow.
Response time is about 10+s, it takes a long time to click any button.

Source code / logs
 sudo docker logs acd289fe436c                                                                                                                                                           Making staticfiles
Initializing database
Operations to perform:
  Apply all migrations: admin, api, auth, authtoken, contenttypes, sessions, social_django
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying api.0001_initial... OK
  Applying api.0002_speech2text... OK
  Applying api.0002_project_single_class_classification... OK
  Applying api.0003_merge_20200612_0205... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying sessions.0001_initial... OK
  Applying social_django.0001_initial... OK
  Applying social_django.0002_add_related_name... OK
  Applying social_django.0003_alter_email_max_length... OK
  Applying social_django.0004_auto_20160423_0400... OK
  Applying social_django.0005_auto_20160727_2333... OK
  Applying social_django.0006_partial... OK
  Applying social_django.0007_code_timestamp... OK
  Applying social_django.0008_partial_timestamp... OK
Role created successfully "project_admin"
Role created successfully "annotator"
Role created successfully "annotation_approver"
Creating admin
Setting password for User admin.
Superuser created successfully.
Starting django
[2020-11-18 08:32:56 +0000] [34] [INFO] Starting gunicorn 19.9.0
[2020-11-18 08:32:56 +0000] [34] [INFO] Listening at: http://0.0.0.0:8000 (34)
[2020-11-18 08:32:56 +0000] [34] [INFO] Using worker: sync
[2020-11-18 08:32:56 +0000] [37] [INFO] Booting worker with pid: 37
[2020-11-18 08:32:56 +0000] [38] [INFO] Booting worker with pid: 38
Making staticfiles
Initializing database
Operations to perform:
  Apply all migrations: admin, api, auth, authtoken, contenttypes, sessions, social_django
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Creating admin
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 59, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/doccano/app/server/management/commands/create_admin.py", line 22, in handle
    super().handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 184, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/models.py", line 161, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/models.py", line 144, in _create_user
    user.save(using=self._db)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
Starting django
[2020-11-18 12:58:50 +0000] [34] [INFO] Starting gunicorn 19.9.0
[2020-11-18 12:58:50 +0000] [34] [INFO] Listening at: http://0.0.0.0:8000 (34)
[2020-11-18 12:58:50 +0000] [34] [INFO] Using worker: sync
[2020-11-18 12:58:50 +0000] [37] [INFO] Booting worker with pid: 37
[2020-11-18 12:58:50 +0000] [38] [INFO] Booting worker with pid: 38
Not Found: /KingViewWeb/
Not Found: /webconfig.ini

**Comment by icoxfog417** [comment]
Thank you for providing the information and log. Your log suggests the exception occurs (For that reason, the application will not launch correctly). 
Please delete the doccano volume and confirm the application launch correctly. If performance is slow despite a successful startup, please raise a new issue.

related issue (already solved) https://github.com/doccano/doccano/issues/965
