### ISSUE TITLE
resolve 'vue-chartjs/es/BaseCharts/Doughnut

### ISSUE THREAD

**Issue by tahirahmad2030** [doccano/doccano#1059]
How to reproduce the problem
---------

I try to run doccanno without a docker-compose so that I can know the flow and debug what is happening with the code to contribute further.

I ran `python manage runserver` which runs fine but when I click on the link `Starting development server at http://127.0.0.1:8000/` it throws error 

```Internal Server Error: /
Traceback (most recent call last):
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle
    tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/webpack_loader/utils.py", line 45, in get_as_tags
    bundle = _get_bundle(bundle_name, extension, config)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/webpack_loader/utils.py", line 23, in _get_bundle
    bundle = get_loader(config).get_bundle(bundle_name)
  File "/home/tahir/anaconda2/envs/apis/lib/python3.6/site-packages/webpack_loader/loader.py", line 97, in get_bundle
    raise WebpackError(error)
webpack_loader.exceptions.WebpackError: 
            ModuleNotFoundError in 
            Module not found: Error: Can't resolve 'vue-chartjs/es/BaseCharts/Doughnut' in '/home/tahir/doccano/app/server/static/components'
```

```bash
# copy-paste the error message here
```

Your Environment
---------

*   Operating System: Ununtu 16.04
*   Python Version Used: 3.6
*   When you install doccano: 18/11/2020
*   How did you install doccano (Heroku button etc):no

**Comment by Hironsan** [comment]
See https://github.com/doccano/doccano/blob/master/docs/getting-started.md#python
