### ISSUE TITLE
Backend container always dies on startup

### ISSUE THREAD

**Issue by alexmadey-oc** [doccano/doccano#1091]
I'm unable to start doccano locally. The backend container always dies.

How to reproduce the problem
---------
I ran the following commands
$ git clone https://github.com/doccano/doccano.git
$ cd doccano
$ docker-compose -f docker-compose.prod.yml up

```
Creating network "doccano_default" with the default driver
Creating doccano_postgres_1 ... done
Creating doccano_frontend_1 ... done
Creating doccano_backend_1  ... done
Creating doccano_nginx_1    ... done
Attaching to doccano_postgres_1, doccano_frontend_1, doccano_backend_1, doccano_nginx_1
backend_1   | Making staticfiles
postgres_1  | 
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  | 
backend_1   | Executing collectstatic
postgres_1  | 2020-12-04 07:56:18.363 UTC [1] LOG:  starting PostgreSQL 13.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
postgres_1  | 2020-12-04 07:56:18.363 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2020-12-04 07:56:18.363 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2020-12-04 07:56:18.367 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2020-12-04 07:56:18.372 UTC [20] LOG:  database system was shut down at 2020-12-04 07:50:52 UTC
postgres_1  | 2020-12-04 07:56:18.376 UTC [1] LOG:  database system is ready to accept connections
doccano_frontend_1 exited with code 0
backend_1   | Traceback (most recent call last):
backend_1   |   File "manage.py", line 15, in <module>
backend_1   |     execute_from_command_line(sys.argv)
backend_1   |   File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
backend_1   |     utility.execute()
backend_1   |   File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
backend_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend_1   |   File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
backend_1   |     self.execute(*args, **cmd_options)
backend_1   |   File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
backend_1   |     output = self.handle(*args, **options)
backend_1   |   File "/usr/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
backend_1   |     collected = self.collect()
backend_1   |   File "/usr/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 105, in collect
backend_1   |     for path, storage in finder.list(self.ignore_patterns):
backend_1   |   File "/usr/lib/python3.6/site-packages/django/contrib/staticfiles/finders.py", line 131, in list
backend_1   |     for path in utils.get_files(storage, ignore_patterns):
backend_1   |   File "/usr/lib/python3.6/site-packages/django/contrib/staticfiles/utils.py", line 23, in get_files
backend_1   |     directories, files = storage.listdir(location)
backend_1   |   File "/usr/lib/python3.6/site-packages/django/core/files/storage.py", line 315, in listdir
backend_1   |     for entry in os.scandir(path):
backend_1   | FileNotFoundError: [Errno 2] No such file or directory: '/app/client/dist/static'
doccano_backend_1 exited with code 1

```

Your Environment
---------

*   Operating System: Mac OS 10.15.7
*   Python Version Used: 3.6
*   When you install doccano: today
*   How did you install doccano (Heroku button etc): locally

**Comment by huanbd** [comment]
I have same error, my env is Centos7. But when I deploy in Unbuntu, It run Ok
