### ISSUE TITLE
Failed to run on Ubuntu python3.7 and python3.8

### ISSUE THREAD

**Issue by wyfSunflower** [doccano/doccano#1118]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:Ubuntu20.04
*   Python Version Used:python3
*   When you install doccano:today
*   How did you install doccano (Heroku button etc):pip install
*Failed to run in python3.7
Setup Database.
Traceback (most recent call last):
  File "/home/mingzhu/anaconda3/lib/python3.7/site-packages/app/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/mingzhu/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mingzhu/anaconda3/lib/python3.7/site-packages/app/app/settings.py", line 283
    if (spec := importlib.util.find_spec(name)) is not None:
             ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/mingzhu/anaconda3/lib/python3.7/site-packages/app/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/mingzhu/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mingzhu/anaconda3/lib/python3.7/site-packages/app/app/settings.py", line 283
    if (spec := importlib.util.find_spec(name)) is not None:
             ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/home/mingzhu/anaconda3/lib/python3.7/site-packages/app/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/mingzhu/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mingzhu/anaconda3/lib/python3.7/site-packages/app/app/settings.py", line 283
    if (spec := importlib.util.find_spec(name)) is not None:
             ^
SyntaxError: invalid syntax
Create admin user.
Traceback (most recent call last):
  File "/home/mingzhu/anaconda3/lib/python3.7/site-packages/app/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/mingzhu/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mingzhu/anaconda3/lib/python3.7/site-packages/app/app/settings.py", line 283
    if (spec := importlib.util.find_spec(name)) is not None:
             ^
SyntaxError: invalid syntax
Starting server with port 8000.
Traceback (most recent call last):
  File "/home/mingzhu/anaconda3/lib/python3.7/site-packages/app/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mingzhu/.local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/mingzhu/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mingzhu/anaconda3/lib/python3.7/site-packages/app/app/settings.py", line 283
    if (spec := importlib.util.find_spec(name)) is not None:
             ^
SyntaxError: invalid syntax

**Comment by wyfSunflower** [comment]
Failed to run in python3.8
Setup Database.
Traceback (most recent call last):
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/app/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/app/api/models.py", line 11, in <module>
    from polymorphic.models import PolymorphicModel
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/polymorphic/models.py", line 11, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/utils/__init__.py)
Traceback (most recent call last):
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/app/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/app/api/models.py", line 11, in <module>
    from polymorphic.models import PolymorphicModel
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/polymorphic/models.py", line 11, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/utils/__init__.py)
Traceback (most recent call last):
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/app/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/app/api/models.py", line 11, in <module>
    from polymorphic.models import PolymorphicModel
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/polymorphic/models.py", line 11, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/utils/__init__.py)
Create admin user.
Traceback (most recent call last):
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/app/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/app/api/models.py", line 11, in <module>
    from polymorphic.models import PolymorphicModel
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/polymorphic/models.py", line 11, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/utils/__init__.py)
Starting server with port 8000.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/app/api/models.py", line 11, in <module>
    from polymorphic.models import PolymorphicModel
  File "/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/polymorphic/models.py", line 11, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/home/mingzhu/anaconda3/envs/py38/lib/python3.8/site-packages/django/utils/__init__.py)

**Comment by fjen** [comment]
First error is fixed in #1108 which is in the current version that is on pypi. Please update doccano.

On the second error: (an older version?) of django-polymorphic seems to be importing django.utils.six, that does not exist in django 3 anymore. Maybe update your dependencies?
