### ISSUE TITLE
Cannot login to default admin account

### ISSUE THREAD

**Issue by vnnoder** [doccano/doccano#1130]
After deploying Doccano, I can't login to the default admin account. The server returns "Wrong password or username" message. I tried both installing with Heroku button and installing docker or docker-compose on AWS Linux / AWS Ubuntu and receive the same error log below. It seems related to azuread_tenant.py. 

How to reproduce the problem
---------
I tried both installing with Heroku button and installing docker or docker-compose on AWS Linux. 

```bash
Internal Server Error: /v1/auth-token
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 468, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 494, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/authtoken/views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 235, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 433, in run_validation
    value = self.validate(value)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/authtoken/serializers.py", line 20, in validate
    user = authenticate(request=self.context.get('request'),
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 66, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/usr/local/lib/python3.8/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/social_core/backends/azuread_tenant.py", line 6, in <module>
    from jwt import DecodeError, ExpiredSignature, decode as jwt_decode
ImportError: cannot import name 'ExpiredSignature' from 'jwt' (/usr/local/lib/python3.8/site-packages/jwt/__init__.py)
```

Your Environment
---------

*   Operating System: Amazon Linux 2 
*   Python Version Used: 3.8
*   When you install doccano: yesterday
*   How did you install doccano (Heroku button etc): docker, docker-compose, Heroku button

**Comment by zenggo** [comment]
Same problem here.

It may because the PyJWT version is incompatible, refer to [this issue of social_core](https://github.com/python-social-auth/social-core/pull/532/files)

I fix it by adding `PyJWT>=1.4.0,<2` to the doccano/app/requirements.txt.

**Comment by Code4SAFrankie** [comment]
I can't even find the part where the documentation says what the default admin password is. It talks about using the django admin, but if I go to `http://localhost:8000/admin` I get a 404 error.

**Comment by zenggo** [comment]
@Code4SAFrankie 
It is in the `docker-compose.dev.yml` and `docker-compose.prod.yml`
You can modify them before start the service.

**Comment by Code4SAFrankie** [comment]
Did a 
`.\python.exe -m pip install --upgrade pyjwt==1.4.0`
and 
`python manage.py migrate`
`python manage.py create_roles`
`python manage.py create_admin --noinput --username "admin" --email "admin@example.com" --password "password"`
`python manage.py runserver`
and
`http://127.0.0.1:8000/admin`
after that the following worked
`.\doccano.exe --username admin --password password`

**Comment by vnnoder** [comment]
Thanks for the direction @zenggo @Code4SAFrankie. In my case, it works after I added pyjwt==1.7.1 to requirements.txt

**Comment by STHSF** [comment]
I also encountered this problem. you need to logout Django administration
![image](https://user-images.githubusercontent.com/8037442/103255640-03702c00-49c5-11eb-85e4-cc997fa2b37c.png)

**Comment by Lijiachen1018** [comment]
> I can't even find the part where the documentation says what the default admin password is. It talks about using the django admin, but if I go to `http://localhost:8000/admin` I get a 404 error.

I also got this error when trying to create a new user, and found a solution.
To create an admin user by `python manage.py createsuperuser`. 
You can also change password in command line with `python manage.py changepassword <user_name>`
To create a user by:

```python
# go to app/ folder where you can find the manage.py file
python manage.py shell
>>> from django.contrib.auth.models import User
>>> user = User.objects.create_user('user_name','email_address','password')
>>> user.is_superuser = False
>>> user.is_staff = False
>>> user.save()
>>> User.objects.all()
<QuerySet [<User: admin>, <User: user_name>]>
# successfully create a new user.
```
