### ISSUE TITLE
TemplateDoesNotExist / index.html

### ISSUE THREAD

**Issue by MohamedOsama1996** [doccano/doccano#1181]
when i installed doccano using pip and i ran the server on 127.0.0.1:800 the above error appeared any solution ???

**Comment by Hironsan** [comment]
We need more information to solve the problem.

- OS
- Python version
- Package version
- Stack trace
- etc

**Comment by MohamedOsama1996** [comment]
OS : Windows 10 ( 64-bit )
Python version :  3.7.5
package version : 1.1.1
Stack Trace : 
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Mohamed\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Mohamed\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\Mohamed\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\Mohamed\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Mohamed\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Mohamed\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
[28/Jan/2021 16:02:21] "GET / HTTP/1.1" 500 88057
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\Mohamed\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Mohamed\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\Mohamed\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\Mohamed\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\Mohamed\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\Mohamed\AppData\Local\Programs\Python\Python37\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
[28/Jan/2021 16:02:22] "GET /favicon.ico HTTP/1.1" 500 87960

also i would like to know how to access the doccano api .. i mean how can i send for example a text file from my custom frontend and receive a response with a labeled text file from doccano api ... to clarify more i want to send a textfile for example on localhost:127.0.0.1:8000/label-file and get a response a labeled file

**Comment by Hironsan** [comment]
This may be related to https://github.com/doccano/doccano/issues/1159 and Windows. I tested it on Mac and Ubuntu but it works well.

Unfortunately, I don't have Windows PC so I can't reproduce this problem.
I want someone who has Windows to investigate the cause.

**Comment by LiangXD** [comment]
how did you solution this problem
