### ISSUE TITLE
Help needed to import dataset with labels

### ISSUE THREAD

**Issue by akdanwlf** [doccano/doccano#1202]
How to reproduce the behaviour
---------

Help needed to import a labeled dataset for a Sequence Labelling project. I have verified the file to check for UTF-8 encoding, and each JSON is validated. 

On choosing Dataset -> Actions -> Import Dataset -> JSONL, File Input -> Upload to import the following JSON with labels, similar to mentioned in the [Import and Export File Formats](https://github.com/doccano/doccano/wiki/Import-and-Export-File-Formats), I get an error `The file(s) could not be uploaded. Maybe invalid format. Please check available formats and the following file(s): test.json`

> {"text": "EU rejects German call to boycott British lamb.", "labels": [ [0, 2, "ORG"], [11, 17, "MISC"]]}
> {"text": "Peter Blackburn", "labels": [ [0, 15, "PERSON"] ]}
> {"text": "President Obama", "labels": [ [10, 15, "PERSON"] ]}

If I try with the following JSON without labels as suggested in [doccano tutorial](https://doccano.github.io/doccano/tutorial/), there seems to be no problem

> {"text": "EU rejects German call to boycott British lamb."}
> {"text": "Peter Blackburn"}
> {"text": "President Obama"}

Am I uploading the dataset with the labels in the wrong place? Can someone point me to a doc or reference where it's mentioned about uploading a dataset with labels?

I did come across these tickets but couldn't find anything useful from them: #11, #197, #408, #681, #848

docker logs:

> Internal Server Error: /v1/projects/1/docs/upload
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
>     return view_func(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
>     response = self.handle_exception(exc)
>   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
>     self.raise_uncaught_exception(exc)
>   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
>     raise exc
>   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
>     response = handler(request, *args, **kwargs)
>   File "/doccano/app/api/views.py", line 303, in post
>     self.save_file(
>   File "/doccano/app/api/views.py", line 318, in save_file
>     storage.save(user)
>   File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
>     return func(*args, **kwds)
>   File "/doccano/app/api/utils.py", line 137, in save
>     unique_labels = self.extract_unique_labels(labels)
>   File "/doccano/app/api/utils.py", line 147, in extract_unique_labels
>     return set(itertools.chain(*labels))
> TypeError: unhashable type: 'list'

My Environment
---------

*   Operating System: Windows 10
*   Python Version Used: 3.7.9
*   When you install doccano: Feb13 2021
*   How did you install doccano (Heroku button etc): docker

**Comment by akdanwlf** [comment]
Quick update on the above issue, I tested the same again by cloning the repo and running using docker-compose there is no error able to import the dataset just fine. Similarly, I have used the azure deploy template and that is also working fine. Only installing through docker seems to be the problem.
