### ISSUE TITLE
Container unable to start due to django.core.exception

### ISSUE THREAD

**Issue by kamoclav** [doccano/doccano#1215]
How to reproduce the behaviour
---------
When deploying Doccano to an Azure Web App through the azuredeploy script, the deployment is successful but the container is unable to start due to a django configuration error.

2021-02-24T02:00:04.252746335Z Making staticfiles
2021-02-24T02:00:04.289508141Z Initializing database
2021-02-24T02:00:08.807670869Z Traceback (most recent call last):
2021-02-24T02:00:08.807699170Z   File "manage.py", line 15, in <module>
2021-02-24T02:00:08.807704870Z     execute_from_command_line(sys.argv)
2021-02-24T02:00:08.807709070Z   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
2021-02-24T02:00:08.807715070Z     utility.execute()
2021-02-24T02:00:08.807718971Z   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
2021-02-24T02:00:08.807723371Z     self.fetch_command(subcommand).run_from_argv(self.argv)
2021-02-24T02:00:08.807727271Z   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
2021-02-24T02:00:08.807731771Z     self.execute(*args, **cmd_options)
2021-02-24T02:00:08.807735671Z   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
2021-02-24T02:00:08.807739771Z     output = self.handle(*args, **options)
2021-02-24T02:00:08.807743572Z   File "/doccano/app/api/management/commands/wait_for_db.py", line 22, in handle
2021-02-24T02:00:08.807747572Z     connection.ensure_connection()
2021-02-24T02:00:08.807751472Z   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
2021-02-24T02:00:08.807755772Z     return func(*args, **kwargs)
2021-02-24T02:00:08.807759572Z   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
2021-02-24T02:00:08.807763772Z     self.connect()
2021-02-24T02:00:08.807767672Z   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
2021-02-24T02:00:08.807771673Z     return func(*args, **kwargs)
2021-02-24T02:00:08.807775673Z   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 199, in connect
2021-02-24T02:00:08.807779673Z     conn_params = self.get_connection_params()
2021-02-24T02:00:08.807783473Z   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 157, in get_connection_params
2021-02-24T02:00:08.807787673Z     raise ImproperlyConfigured(
2021-02-24T02:00:08.807791473Z django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the NAME value.

Your Environment
---------

Deployed through the one click azure deployment button https://camo.githubusercontent.com/72bcd8efbce44223148091cf74c3e6a37d3935f664f713bc53d312aa0d77d8e9/68747470733a2f2f617a7572656465706c6f792e6e65742f6465706c6f79627574746f6e2e737667

**Comment by tuomastik** [comment]
Running into the same error on AWS via one-click deployment. Ping @Hironsan 

```
[ec2-user@ip-10-0-1-247 ~]$ sudo docker ps -a
CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS                     PORTS                                                                    NAMES
1a472710decc   doccano_nginx          "nginx -g 'daemon of…"   6 minutes ago   Up 6 minutes               80/tcp, 0.0.0.0:80->8080/tcp                                             doccano_nginx_1
05331624de0e   doccano_celery         "/opt/bin/prod-celer…"   7 minutes ago   Exited (1) 6 minutes ago                                                                            doccano_celery_1
0b1f683900a7   doccano_backend        "/opt/bin/prod-djang…"   7 minutes ago   Exited (1) 6 minutes ago                                                                            doccano_backend_1
536f1d1d1a6d   rabbitmq:3.8           "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes               4369/tcp, 5671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:5672->5672/tcp   doccano_rabbitmq_1
8bf449d16b57   postgres:13.1-alpine   "docker-entrypoint.s…"   7 minutes ago   Exited (1) 7 minutes ago                                                                            doccano_postgres_1

[ec2-user@ip-10-0-1-247 ~]$ sudo docker logs 0b1f683900a7
Making staticfiles
Executing collectstatic
Filepond app init: Creating temporary file upload directory </backend/filepond-temp-uploads>

181 static files copied to '/backend/staticfiles', 567 post-processed.
Initializing database
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/backend/api/management/commands/wait_for_db.py", line 22, in handle
    connection.ensure_connection()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 199, in connect
    conn_params = self.get_connection_params()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 157, in get_connection_params
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the NAME value.
```

**Comment by ahtokca** [comment]
Same here `django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured`
