### ISSUE TITLE
Getting errors during annotations, missing labels

### ISSUE THREAD

**Issue by johann-petrak** [doccano/doccano#1236]
I am getting exceptions on the log like this:

```
Internal Server Error: /v1/projects/1/docs/28/annotations
Traceback (most recent call last):
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/views.py", line 414, in initial
    self.perform_authentication(request)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/request.py", line 227, in user
    self._authenticate()
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/authentication.py", line 196, in authenticate
    return self.authenticate_credentials(token)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/authentication.py", line 201, in authenticate_credentials
    token = model.objects.select_related('user').get(key=key)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked
```

and 

```
Internal Server Error: /v1/projects/1/docs/40/annotations
Traceback (most recent call last):
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: api_documentannotation.document_id, api_documentannotation.user_id, api_documentannotation.label_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/johann/doccano/app/api/views.py", line 225, in create
    return super().create(request, args, kwargs)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/johann/doccano/app/api/views.py", line 228, in perform_create
    serializer.save(document_id=self.kwargs['doc_id'], user=self.request.user)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/rest_framework/serializers.py", line 939, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/johann/software/anaconda3/envs/doccano/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: api_documentannotation.document_id, api_documentannotation.user_id, api_documentannotation.label_id
```
And the GUI is sometimes showing popup dialogs mentioning a server 500 error. 

What is more worrying is that after assigning a label to an example and moving on to other examples, some of the examples then do not have any label, so the annotation was unsuccessful, but this was not directly visible in the GUI. 

This happens *sometimes* so it is hard to find out what could cause this. 

I have installed doccano from git, commit 8d6d41f85adef4f80d21fdcbd4e07561ac74cd  and I am using the patch from https://github.com/doccano/doccano/issues/1191

I am running doccano using Python 3.8.5 
```
gunicorn --bind="0.0.0.0:8000" --workers=4 app.wsgi --timeout 300
```
in the app subdirectory after setting up pretty much like in https://github.com/doccano/doccano/issues/1192 

Does Doccano have a problem running with several workers using gunicorn?

**Comment by johann-petrak** [comment]
What is even more irritating is that the label from the previous example is sometimes shown for the next example, or that no label from the previous example is shown even though it has just been assigned.
However, when reloading the whole page, the proper situation is usually shown. 

This is really frustrating because from initial tests where things seemed to work, we have made a decision to use doccano for the annotation exercise, but with these problems it is hard to ensure that everything gets annotated properly.

**Comment by johann-petrak** [comment]
We have now decided to do an emergency change of plans and do the annotations in automatically created Excel sheets with support scripts for extraction and consolidiation instead. 
These problems together with the fact that single-label classification annotation is not really properly supported (#1191) make it just too risky to use it for this kind of annotation task.

**Comment by kuraga** [comment]
I hope there are no these issues in 1.2.1 version.

**Comment by MarkProjectRepo** [comment]
Same issue happening for me, had to just switch utilities all together.

**Comment by Hironsan** [comment]
Now single label classification is officially supported.
- https://github.com/doccano/doccano/pull/1261

Is there still this problem?
If so, I want to know exactly the procedure to reproduce the problem.

**Comment by kuraga** [comment]
@Hironsan ,
do you expect this was single-classification issue, only?

> Does Doccano have a problem running with several workers using gunicorn?

Any thoughts here?

**Comment by Hironsan** [comment]
Anyway, we need to reproduce the problem for solving the problem.
So I want to know the environment and the procedure to reproduce the problem.

**Comment by kuraga** [comment]
@Hironsan Well, anyway
```
django.db.utils.IntegrityError: UNIQUE constraint failed: api_documentannotation.document_id, api_documentannotation.user_id, api_documentannotation.label_id
```
could be fixed by #1261 but how this:
```
sqlite3.OperationalError: database is locked
```
could be fixed by it?

I afraid @johann-petrak and @MarkProjectRepo will be unable / will not reproduce the error.
But it won't say anything, sadly...

But error is scaring enough.

**Comment by Hironsan** [comment]
OK. I was able to reproduce `database is locked`.

This may be a sqlite3 problem(related to threading).
An alternative is to use PostgreSQL. It does not occur the problem.

**Comment by kuraga** [comment]
Strange if Django + gunicorn really don't open different connections on `--workers=4` but https://docs.djangoproject.com/en/3.1/ref/databases/#database-is-locked-errors. Stranger that even in that doccs I don't see if Django opens different connections or shares the one.

@Hironsan , way to start doccano by @johann-petrak is undocumented-so-forbiden, yes?

**Comment by patrick-tssn** [comment]
did you solve the problem?

**Comment by joaossmacedo** [comment]
Any updates?

**Comment by armandleopold** [comment]
Updates please

**Comment by datalee** [comment]
did you solve the problem?

**Comment by datalee** [comment]
> postgresql

postgresql also has this issue?

**Comment by datalee** [comment]
> Updates please, we have issues with too many threaded connection to postgresql using the app.
postgresql also has this issue?

**Comment by armandleopold** [comment]
me ? @datalee no
