### ISSUE TITLE
Pip installion: Can't setup sqlite db

### ISSUE THREAD

**Issue by Smurphy000** [doccano/doccano#1252]
How to reproduce the problem
---------

Installed with the pip method

After running the __doccano__ command

```bash
Setup Database.
SystemCheckError: System check identified some issues:

ERRORS:
api.AutoLabelingConfig: (fields.E180) SQLite does not support JSONFields.
api.AutoLabelingConfig: (fields.E180) SQLite does not support JSONFields.

Traceback (most recent call last):
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: api_role

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\app\manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\core\management\base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\app\api\management\commands\create_roles.py", line 16, in handle
    if Role.objects.filter(name=role_name).exists():
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\models\query.py", line 809, in exists
    return self.query.has_results(using=self.db)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\models\sql\query.py", line 535, in has_results
    return compiler.has_results()
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\models\sql\compiler.py", line 1126, in has_results
    return bool(self.execute_sql(SINGLE))
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: api_role
Create admin user.

You have 38 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, api, auth, authtoken, contenttypes, sessions, social_django.
Run 'python manage.py migrate' to apply them.
Traceback (most recent call last):
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auth_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\app\manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\core\management\base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\contrib\auth\management\commands\createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\app\api\management\commands\create_admin.py", line 22, in handle
    super().handle(*args, **options)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\contrib\auth\management\commands\createsuperuser.py", line 176, in handle
    error_msg = self._validate_username(username, verbose_field_name, database)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\contrib\auth\management\commands\createsuperuser.py", line 234, in _validate_username
    self.UserModel._default_manager.db_manager(database).get_by_natural_key(username)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\contrib\auth\base_user.py", line 45, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\models\query.py", line 425, in get
    num = len(clone)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\models\query.py", line 269, in __len__
    self._fetch_all()
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\models\query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\models\query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "c:\users\conner\desktop\stockspeak-research\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auth_user
Starting server with port 8000.
```

I am just trying to setup a local environment, and thought that pip would be the quickest method.
The big errors I am seeing are the api_role and auth_user table not being created, which is probably because of 
```bash
ERRORS:
api.AutoLabelingConfig: (fields.E180) SQLite does not support JSONFields.
api.AutoLabelingConfig: (fields.E180) SQLite does not support JSONFields.
```

but do I need to setup a different database (such as postgres?) and how would that be easily configurable with doccano

Your Environment
---------

*   Operating System: Windows 10
*   Python Version Used: 3.7
*   When you install doccano: pip
*   How did you install doccano (Heroku button etc):

**Comment by Hironsan** [comment]
This may be related to the SQLite3 version. JSONField is supported on SQLite 3.9.0+.
- [JSONField](https://docs.djangoproject.com/en/3.1/ref/models/fields/#jsonfield)

Please tell me the sqlite version to solve the problem:

```python
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.33.0'
```

A quick alternative for you is to use the Docker version.

**Comment by Smurphy000** [comment]
Hello, your response led me down the correct path. I was using python 3.7 and 3.8, which the django documentation says has the JSON1 feature disabled by default, while 3.9 is enable. I was able to setup using python 3.9 pretty simply!

**Comment by ychuang789** [comment]
I had faced a similar problem when init the doccano, and I solved this problem via following the instruction of [How to Upgrade SQLite3 for Python](https://www.youtube.com/watch?v=urVT5BE3XCM) to update the dll file of sqlite and it works. By the way, I am using python 3.8.
