### ISSUE TITLE
Dataset / Projects vanished

### ISSUE THREAD

**Issue by argideritzalpea** [doccano/doccano#1269]
While I was annotating labels in a session as the `admin`, my computer shut down in a controlled, timed restart while my doccano server was still active and up. After the restart and activating the doccano server again from the command line, I was expectedly still logged in as the superuser, though my projects did not load in the UI (there was a forever 'loading' type indicator on the "Projects" page. I looked at the logs and saw `'GET /v1/projects HTTP/1.1' 403 27` explaining the page load problem.

When I "Cmd+C" to shutdown the server, I also see the following traceback message in the command terminal:
```Traceback (most recent call last):

  File "c:\anaconda\envs\doccano_env\lib\wsgiref\handlers.py", line 138, in run

    self.finish_response()

  File "c:\anaconda\envs\doccano_env\lib\wsgiref\handlers.py", line 138, in run

    self.finish_response()

  File "c:\anaconda\envs\doccano_env\lib\wsgiref\handlers.py", line 181, in finish_response

    self.finish_content()

  File "c:\anaconda\envs\doccano_env\lib\wsgiref\handlers.py", line 180, in finish_response

    self.write(data)

  File "c:\anaconda\envs\doccano_env\lib\wsgiref\handlers.py", line 274, in write

    self.send_headers()

  File "c:\anaconda\envs\doccano_env\lib\wsgiref\handlers.py", line 310, in finish_content

    self.send_headers()

  File "c:\anaconda\envs\doccano_env\lib\wsgiref\handlers.py", line 332, in send_headers

    self.send_preamble()

  File "c:\anaconda\envs\doccano_env\lib\wsgiref\handlers.py", line 332, in send_headers

    self.send_preamble()

  File "c:\anaconda\envs\doccano_env\lib\wsgiref\handlers.py", line 255, in send_preamble

    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')

  File "c:\anaconda\envs\doccano_env\lib\wsgiref\handlers.py", line 453, in _write

    result = self.stdout.write(data)

  File "c:\anaconda\envs\doccano_env\lib\wsgiref\handlers.py", line 255, in send_preamble

    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')

  File "c:\anaconda\envs\doccano_env\lib\wsgiref\handlers.py", line 453, in _write

    result = self.stdout.write(data)

  File "c:\anaconda\envs\doccano_env\lib\socketserver.py", line 803, in write

    self._sock.sendall(b)

ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

  File "c:\anaconda\envs\doccano_env\lib\socketserver.py", line 803, in write

    self._sock.sendall(b)

ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

[26/Mar/2021 09:50:09] "GET /static/_nuxt/runtime.e3eb21a.js HTTP/1.1" 500 59

```
and
``` 

 

During handling of the above exception, another exception occurred:

 

  File "c:\anaconda\envs\doccano_env\lib\site-packages\django\core\servers\basehttp.py", line 197, in handle_one_request

    handler.run(self.server.get_app())

Traceback (most recent call last):

  File "c:\anaconda\envs\doccano_env\lib\wsgiref\handlers.py", line 144, in run

    self.close()

  File "c:\anaconda\envs\doccano_env\lib\socketserver.py", line 654, in process_request_thread

    self.finish_request(request, client_address)

  File "c:\anaconda\envs\doccano_env\lib\site-packages\django\core\servers\basehttp.py", line 114, in close

    super().close()

  File "c:\anaconda\envs\doccano_env\lib\wsgiref\simple_server.py", line 35, in close

    self.status.split(' ',1)[0], self.bytes_sent

AttributeError: 'NoneType' object has no attribute 'split'

  File "c:\anaconda\envs\doccano_env\lib\socketserver.py", line 364, in finish_request

    self.RequestHandlerClass(request, client_address, self)

----------------------------------------

  File "c:\anaconda\envs\doccano_env\lib\socketserver.py", line 724, in __init__

    self.handle()

  File "c:\anaconda\envs\doccano_env\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle

    self.handle_one_request()

  File "c:\anaconda\envs\doccano_env\lib\site-packages\django\core\servers\basehttp.py", line 197, in handle_one_request

    handler.run(self.server.get_app())

  File "c:\anaconda\envs\doccano_env\lib\wsgiref\handlers.py", line 144, in run

    self.close()

  File "c:\anaconda\envs\doccano_env\lib\site-packages\django\core\servers\basehttp.py", line 114, in close

    super().close()

  File "c:\anaconda\envs\doccano_env\lib\wsgiref\simple_server.py", line 35, in close

    self.status.split(' ',1)[0], self.bytes_sent

AttributeError: 'NoneType' object has no attribute 'split'

```
I get the following when starting up the server:
```Setup Database.

Operations to perform:

  Apply all migrations: admin, api, auth, authtoken, contenttypes, sessions, social_django

Running migrations:

  No migrations to apply.

Create admin user.

User admin already exists.

Setting password for User admin.

Starting server with port 8000.

Performing system checks...

 

System check identified no issues (0 silenced).

March 26, 2021 - 10:12:53

Django version 3.1.7, using settings 'app.settings'

Starting development server at http://0.0.0.0:8000/

Quit the server with CTRL-BREAK.

[26/Mar/2021 10:12:54] "GET / HTTP/1.1" 200 3111

[26/Mar/2021 10:12:54] "GET /static/_nuxt/runtime.e3eb21a.js HTTP/1.1" 304 0

[26/Mar/2021 10:12:54] "GET /static/_nuxt/commons/app.79d7b3a.js HTTP/1.1" 304 0

[26/Mar/2021 10:12:54] "GET /static/_nuxt/vendors~app.a5bea04.js HTTP/1.1" 304 0

[26/Mar/2021 10:12:54] "GET /static/_nuxt/app.a30b7d6.js HTTP/1.1" 304 0

[26/Mar/2021 10:12:54] "GET /static/_nuxt/pages/index.23ed619.js HTTP/1.1" 304 0

[26/Mar/2021 10:12:54] "GET /static/_nuxt/lang-en.f27c931.js HTTP/1.1" 304 0

[26/Mar/2021 10:12:54] "GET /static/_nuxt/img/vbanner.0d5edfa.jpg HTTP/1.1" 304 0

[26/Mar/2021 10:12:54] "GET /static/_nuxt/img/icon.8612b9c.png HTTP/1.1" 304 0

[26/Mar/2021 10:12:55] "GET /favicon.ico HTTP/1.1" 200 3111

```

What are some steps to debug this 403 error and readmit access?

**Comment by argideritzalpea** [comment]
Operating System: Windows
Python Version Used: 3.6
When you install doccano: 2 days ago
How did you install doccano (Heroku button etc): pip

**Comment by argideritzalpea** [comment]
Doccano's default .db writes to the local dir in which doccano was started. Nevertheless, the load times are very long. Closing issue.
