### ISSUE TITLE
Can't create new Custom REST Request model

### ISSUE THREAD

**Issue by gika815** [doccano/doccano#1307]
Trying to create new Auto-labling model (Custom REST request). 
When I press the button "Test" I have "NameError: Custom REST Request is not found" error in Docker logs

Forbidden: /v1/me

[19/Apr/2021 07:55:24] "GET /v1/me HTTP/1.1" 403 58

Forbidden: /v1/me

[19/Apr/2021 07:55:25] "GET /v1/me HTTP/1.1" 403 58

[19/Apr/2021 07:55:34] "POST /v1/auth/login/ HTTP/1.1" 200 50

[19/Apr/2021 07:55:34] "GET /v1/me HTTP/1.1" 200 47

[19/Apr/2021 07:55:34] "GET /v1/projects HTTP/1.1" 200 400

[19/Apr/2021 07:55:39] "GET /v1/projects/1 HTTP/1.1" 200 357

[19/Apr/2021 07:55:40] "GET /v1/projects/1 HTTP/1.1" 200 357

[19/Apr/2021 07:55:41] "GET /v1/projects/1 HTTP/1.1" 200 357

[19/Apr/2021 07:55:41] "GET /v1/projects/1/auto-labeling-configs HTTP/1.1" 200 2

[19/Apr/2021 07:55:42] "GET /v1/projects/1/auto-labeling-templates HTTP/1.1" 200 127

[19/Apr/2021 07:55:42] "GET /v1/projects/1/labels HTTP/1.1" 200 342

[19/Apr/2021 07:55:44] "GET /v1/projects/1/auto-labeling-templates/GCP%20Entity%20Analysis HTTP/1.1" 200 1491

[19/Apr/2021 07:55:45] "GET /v1/projects/1/auto-labeling-templates/Custom%20REST%20Request HTTP/1.1" 200 531

Internal Server Error: /v1/auto-labeling-parameter-testing

Traceback (most recent call last):

File "/src/app/api/views/auto_labeling.py", line 113, in post

model = RequestModelFactory.create(model_name, model_attrs)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/auto_labeling_pipeline/models.py", line 21, in create

subclass = cls.find(model_name)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/auto_labeling_pipeline/models.py", line 30, in find

raise NameError(f'{model_name} is not found.')

NameError: Custom REST Request is not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner

response = get_response(request)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response

response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view

return view_func(*args, **kwargs)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view

return self.dispatch(request, *args, **kwargs)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch

response = self.handle_exception(exc)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception

self.raise_uncaught_exception(exc)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception

raise exc

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch

response = handler(request, *args, **kwargs)

File "/src/app/api/views/auto_labeling.py", line 115, in post

model = RequestModelFactory.find(model_name)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/auto_labeling_pipeline/models.py", line 30, in find

raise NameError(f'{model_name} is not found.')

NameError: Custom REST Request is not found.

[19/Apr/2021 07:56:35] "POST /v1/auto-labeling-parameter-testing HTTP/1.1" 500 115180

Internal Server Error: /v1/auto-labeling-parameter-testing

Traceback (most recent call last):

File "/src/app/api/views/auto_labeling.py", line 113, in post

model = RequestModelFactory.create(model_name, model_attrs)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/auto_labeling_pipeline/models.py", line 21, in create

subclass = cls.find(model_name)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/auto_labeling_pipeline/models.py", line 30, in find

raise NameError(f'{model_name} is not found.')

NameError: Custom REST Request is not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner

response = get_response(request)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response

response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view

return view_func(*args, **kwargs)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view

return self.dispatch(request, *args, **kwargs)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch

response = self.handle_exception(exc)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception

self.raise_uncaught_exception(exc)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception

raise exc

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch

response = handler(request, *args, **kwargs)

File "/src/app/api/views/auto_labeling.py", line 115, in post

model = RequestModelFactory.find(model_name)

File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.8/site-packages/auto_labeling_pipeline/models.py", line 30, in find

raise NameError(f'{model_name} is not found.')

NameError: Custom REST Request is not found.

[19/Apr/2021 08:10:41] "POST /v1/auto-labeling-parameter-testing HTTP/1.1" 500 115361

Environment
---------

*   Operating System: windows 10
*   Python Version Used: 3.8.6 (container)
*   When you install doccano: 2021-04-19 
*   How did you install doccano (Heroku button etc): git clone, docker-compose

**Comment by gika815** [comment]
After some code research we find a problem
There is a problem in auto-labeling-pipeline module
location - auto_labeling_pipeline/models.py
class - RequestModelFactory 
classmetod - find()

```
@classmethod
    def find(cls, model_name: str) -> Type[RequestModel]:
        for subclass in RequestModel.__subclasses__():
            if subclass.__name__ == model_name:
                return subclass
        raise NameError(f'{model_name} is not found.')
class CustomRESTRequestModel(RequestModel):
    """
    This allow you to call any REST API.
    """
    url: AnyHttpUrl
    method: Literal['GET', 'POST']
    params: Optional[dict]
    headers: Optional[dict]
    body: Optional[dict]

    class Config:
        title = 'Custom REST Request'
```
You are trying to find model by name, but there is no such name as 'Custom REST Request'. It's a title in a config of class
I create a monkey patch to fix it, but there is another problem. You have no "build" method in CustomRESTRequestModel class. But you are using it in AutoLabelingConfigParameterTest (Doccano/Doccano, app/api/views/auto_labeling.py)
```
class AutoLabelingConfigParameterTest(APIView):
    permission_classes = [IsAuthenticated & IsProjectAdmin]

    def post(self, *args, **kwargs):
        model_name = self.request.data['model_name']
        model_attrs = self.request.data['model_attrs']
        sample_text = self.request.data['text']
        try:
            model = RequestModelFactory.create(model_name, model_attrs)
        except Exception:
            model = RequestModelFactory.find(model_name)
            schema = model.schema()
            required_fields = ', '.join(schema['required']) if 'required' in schema else ''
            raise ValidationError(
                'The attributes does not match the model.'
                'You need to correctly specify the required fields: {}'.format(required_fields)
            )
        try:
            request = model.build()                 <------------------------------------ this
            response = request.send(text=sample_text)
            return Response(response, status=status.HTTP_200_OK)
        except requests.exceptions.ConnectionError:
            raise URLConnectionError
        except botocore.exceptions.ClientError:
            raise AWSTokenError()
        except Exception as e:
            raise e
```

**Comment by maxtrem** [comment]
I'm having the same issue. Is there any fix available. Being able to fetch annotations via REST API would be great!

**Comment by maxtrem** [comment]
There is a related issue here: https://github.com/doccano/doccano/issues/1248

**Comment by gika815** [comment]
ОК, I fix this. There is 2 problemes and you need to do 2 moves to fix this problems
1. "NameError: Custom REST Request is not found"  Error. This error was raised becouse of some changes in auto-labeling-pipeline library.
For fixing it I made monkey patch in Doccano/Doccano project (app/api/views/auto_labeling.py). 
```
@classmethod
def monkey_patched_find(cls, model_name: str) -> Type[RequestModel]:
        for subclass in RequestModel.__subclasses__():
            if subclass.Config.title == model_name:
                return subclass
        raise NameError(f'{model_name} is not found.')

RequestModelFactory.find = monkey_patched_find
```
This is fast solution.
2. After first error you will have 2nd. "RequestModelFactory has no object build()'". For fixing it u need to remove this code (same file,  AutoLabelingConfigParameterTest class)
Good luck

**Comment by maxtrem** [comment]
Thanks for the answer! 
Right now I'm using the docker image, so editing is a bit difficult. It would be great if this could be fixed in the master so that the image is updated.
But I will check this out otherwise, thanks!

**Comment by brokerslurp** [comment]
@Hironsan - can you help with this bug?

**Comment by brokerslurp** [comment]
> ОК, problem solved. There is 2 problemes and you need to do 2 moves to fix this problems
> 
>     1. "NameError: Custom REST Request is not found"  Error. This error was raised becouse of some changes in auto-labeling-pipeline library.
>        For fixing it I made monkey patch in Doccano/Doccano project (app/api/views/auto_labeling.py).
> 
> 
> ```
> @classmethod
> def monkey_patched_find(cls, model_name: str) -> Type[RequestModel]:
>         for subclass in RequestModel.__subclasses__():
>             if subclass.Config.title == model_name:
>                 return subclass
>         raise NameError(f'{model_name} is not found.')
> 
> RequestModelFactory.find = monkey_patched_find
> ```
> 
> This is fast solution.
> 2. After first error you will have 2nd. "RequestModelFactory has no object build()'". For fixing it u need to remove this code (same file, AutoLabelingConfigParameterTest class)
> Good luck

Just in case anyone else is looking to try to hack this together to solve this, here's the exact diff that worked for me:

```diff
diff --git a/backend/api/views/auto_labeling.py b/backend/api/views/auto_labeling.py
index 3919909..2327a28 100644
--- a/backend/api/views/auto_labeling.py
+++ b/backend/api/views/auto_labeling.py
@@ -2,7 +2,7 @@ import botocore.exceptions
 import requests
 from auto_labeling_pipeline.mappings import MappingTemplate
 from auto_labeling_pipeline.menu import Options
-from auto_labeling_pipeline.models import RequestModelFactory
+from auto_labeling_pipeline.models import RequestModelFactory, RequestModel
 from auto_labeling_pipeline.pipeline import pipeline
 from auto_labeling_pipeline.postprocessing import PostProcessor
 from auto_labeling_pipeline.task import TaskFactory
@@ -21,6 +21,15 @@ from ..permissions import IsInProjectOrAdmin, IsProjectAdmin
 from ..serializers import AutoLabelingConfigSerializer


+@classmethod
+def monkey_patched_find(cls, model_name: str): #  -> Type[RequestModel]:
+        for subclass in RequestModel.__subclasses__():
+            if subclass.Config.title == model_name:
+                return subclass
+        raise NameError(f'{model_name} is not found.')
+
+RequestModelFactory.find = monkey_patched_find
+
 class AutoLabelingTemplateListAPI(APIView):
     permission_classes = [IsAuthenticated & IsProjectAdmin]

@@ -120,8 +129,8 @@ class AutoLabelingConfigParameterTest(APIView):
                 'You need to correctly specify the required fields: {}'.format(required_fields)
             )
         try:
-            request = model.build()
-            response = request.send(text=sample_text)
+            # request = model.build()
+            response = model.send(text=sample_text)
             return Response(response, status=status.HTTP_200_OK)
         except requests.exceptions.ConnectionError:
             raise URLConnectionError
```

**Comment by brokerslurp** [comment]
> Thanks for the answer!
> Right now I'm using the docker image, so editing is a bit difficult. It would be great if this could be fixed in the master so that the image is updated.
> But I will check this out otherwise, thanks!

I was able to apply the hack, and I'm using containers as well.  Here's what I had to do to get it working (docs are not all that great in this project):


```bash
# cd /doccano
# docker-compose -f docker-compose.prod.yml down
# docker volume ls
DRIVER    VOLUME NAME
local     0035ba162b840a861275070922bb9af7ba2a393163b8dd864c0c8ac5e5b7f528
local     doccano_media
local     doccano_postgres_data
local     doccano_static_volume
```

Don't delete Postgres Volume!!!


```bash
# docker volume rm 0035ba162b840a861275070922bb9af7ba2a393163b8dd864c0c8ac5e5b7f528 doccano_media doccano_static_volume
```

Edit files...

```bash
# vim backend/api/views/auto_labeling.py
```

Build

```bash
# docker-compose -f docker-compose.prod.yml build
```

Start up:

```bash
# docker-compose -f docker-compose.prod.yml up -d
```

**Comment by rolisz** [comment]
@brokerslurp Can you send a PR with your fixes? Maybe that will help @c-w  or @Hironsan get this bug fixed sooner.

**Comment by brokerslurp** [comment]
> @brokerslurp Can you send a PR with your fixes? Maybe that will help @c-w or @Hironsan get this bug fixed sooner.

Sure, I can do that, but I suspect the "fix" that I performed is really more of a hack and not a proper fix.

**Comment by EnzoNclt** [comment]
Even after this quick hack I still have, in any case, an error 400 as following:

```
backend_1   | Bad Request: /v1/auto-labeling-parameter-testing
backend_1   | [27/May/2021 11:54:37] "POST /v1/auto-labeling-parameter-testing HTTP/1.1" 400 70
```

Do you have any idea from where it could comes , knowing that the network between my back / api and doccano's one seems well connected

**Comment by Mr-IT007** [comment]
Is the problem solved in latest docker image?

**Comment by Mr-IT007** [comment]
Is the problem solved in lastest docker image? @gika815

**Comment by Mr-IT007** [comment]
Is the problem solved in latest docker image? @gika815

**Comment by Mr-IT007** [comment]
Is the problem solved in latest docker image? I have the same problem. @gika815

**Comment by gika815** [comment]
> Is the problem solved in latest docker image? I have the same problem. @gika815

I don't know. I'm using old version with monkey patch. I have no reason to update it right now
