### ISSUE TITLE
AutoLabeling Fails (Internal Server Error) when Label is not already defined

### ISSUE THREAD

**Issue by ghost** [doccano/doccano#1347]
How to reproduce the behaviour
---------
1. Setup auto labeling project with REST endpoint.
2. Rest Endpoint returns Labels that was not defined in the project
3. Turn on auto-label
4. Crash
---------

Stack trace

```python
Internal Server Error: /v1/projects/6/docs/17329/auto-labeling
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/backend/api/views/auto_labeling.py", line 198, in create
    labels = self.transform(labels)
  File "/backend/api/views/auto_labeling.py", line 228, in transform
    label['label'] = project.labels.get(text=label.pop('label')).id
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
api.models.Label.DoesNotExist: Label matching query does not exist.

```

**Comment by brokerslurp** [comment]
> Would you write your environment? Thank you!

I launched my Doccano stack using the CFN template: https://console.aws.amazon.com/cloudformation/home?#/stacks/new?stackName=doccano&templateURL=https://doccano.s3.amazonaws.com/public/cloudformation/template.aws.yaml
