### ISSUE TITLE
No module named 'ffi' when calling doccano init

### ISSUE THREAD

**Issue by tareefroustom** [doccano/doccano#1351]
Hi guys, I'm getting this error when calling doccano init, the installation itself is okay with no dependencies errors raised
---------
(base) C:\Users\troustom>doccano init
Traceback (most recent call last):
  File "c:\users\troustom\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\troustom\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\troustom\Anaconda3\Scripts\doccano.exe\__main__.py", line 4, in <module>
  File "c:\users\troustom\anaconda3\lib\site-packages\backend\cli.py", line 7, in <module>
    import gunicorn.app.base
  File "c:\users\troustom\anaconda3\lib\site-packages\gunicorn\app\base.py", line 11, in <module>
    from gunicorn import util
  File "c:\users\troustom\anaconda3\lib\site-packages\gunicorn\util.py", line 8, in <module>
    import fcntl
  File "c:\users\troustom\anaconda3\lib\site-packages\fcntl.py", line 3, in <module>
    import ffilib
  File "c:\users\troustom\anaconda3\lib\site-packages\ffilib.py", line 2, in <module>
    import ffi
ModuleNotFoundError: No module named 'ffi'

python 3.8.5 on windows

**Comment by Hironsan** [comment]
I could not reproduce this problem in the following environment:

- pip installation v1.3.1
- macOS Mojave 10.14.1
- Python 3.8.5

**Comment by tareefroustom** [comment]
> I could not reproduce this problem in the following environment:
> 
> * pip installation v1.3.1
> * macOS Mojave 10.14.1
> * Python 3.8.5

thanks for your reply mate, no clue, I've looked around for this ffi package but I couldn't find it, apparently it was updated to cffi with no guide on how to migrate, I will keep looking for a solution and keep this thread updated

**Comment by sakshams1990** [comment]
I am stuck as well with fcntl and ffi issue. ffi is being imported fcntl. 
Doccano version - 1.4.0
MS Windows
Python 3.8.4
installed using pip

**Comment by sakshams1990** [comment]
I followed the steps present in https://developers.arcgis.com/python/guide/labeling-text-using-doccano/ and ran doccano using method 1. The latest version is working fine with dockers. Method 2 can be used for running in the local system.
