### ISSUE TITLE
No module named 'fcntl'

### ISSUE THREAD

**Issue by htyhmn** [doccano/doccano#1373]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:windows
*   Python Version Used:3.8
*   When you install doccano:anconda
*   How did you install doccano (Heroku button etc): pip insyall
I run the command 'doccano init',but it was wrong.
ModuleNotFoundError: No module named 'fcntl'

**Comment by Kumaava** [comment]
Facing this issue: 
______________
 doccano init
Traceback (most recent call last):
  File "c:\users\91836\miniconda3\lib\runpy.py", line 194, in _run_module_as_mai
n
    return _run_code(code, main_globals, None,
  File "c:\users\91836\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\91836\miniconda3\Scripts\doccano.exe\__main__.py", line 4, in <
module>
  File "c:\users\91836\miniconda3\lib\site-packages\backend\cli.py", line 7, in
<module>
    import gunicorn.app.base
  File "c:\users\91836\miniconda3\lib\site-packages\gunicorn\app\base.py", line
11, in <module>
    from gunicorn import util
  File "c:\users\91836\miniconda3\lib\site-packages\gunicorn\util.py", line 8, i
n <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
______________

tried installing pip install micropython-fcntl but it didn't help.

**Comment by sakshams1990** [comment]
I followed the steps present in https://developers.arcgis.com/python/guide/labeling-text-using-doccano/ and ran doccano using method 1. The latest version is working fine with dockers. Method 2 can be used for running in the local system.

**Comment by htyhmn** [comment]
> I followed the steps present in https://developers.arcgis.com/python/guide/labeling-text-using-doccano/ and ran doccano using method 1. The latest version is working fine with dockers. Method 2 can be used for running in the local system.
![image](https://user-images.githubusercontent.com/69563759/119327827-fb879000-bcb5-11eb-8b88-a1544390103b.png)


New bug. Do you know what to do with it?

**Comment by sakshams1990** [comment]
On the left side panel , where you see dataset, you import your dataset and create labels by clicking on Labels

**Comment by htyhmn** [comment]
> On the left side panel , where you see dataset, you import your dataset and create labels by clicking on Labels

I have imported the dataset, but the component display is blank.

**Comment by sakshams1990** [comment]
I am actively using doccano and have faced no issue as yet.

**Comment by Hironsan** [comment]
Duplicate to https://github.com/doccano/doccano/issues/1351.

**Comment by d4nielfr4nco** [comment]
The solution provided by @sakshams1990 is targeted for arcgis users and feel more like a workaround to the problem. The supposedly duplicate issue was closed, but the root cause of this particular issue doesn't seem to have been fixed. The current versions of doccano don't seem to be compatible with windows because it uses gunicorn since commit a3a054c3930572850294df42d42675ec410bec5c, and gunicorn uses fcntl.

Is there something you guys can do about this?

**Comment by akhilnegi** [comment]
Workaroud ->` pip install doccano==1.2.4` 

Version 1.2.4 seems to be working on windows. You should be able to spin up a local development server with version 1.2.4 released before [a3a054c ](https://github.com/doccano/doccano/commit/a3a054c3930572850294df42d42675ec410bec5c).

Since gunicorn doesn't work with Windows, the latest version doesn't seem to be compatible with windows, @Hironsan can confirm.

Also, I was able to pip install the latest version(1.4.1) on WSL2(Ubuntu 20.04) on windows without any issue.

**Comment by d4nielfr4nco** [comment]
@akhilnegi Thanks. Your reply could be useful to some users, but in my case I'm using a Windows Server and I'm not able/allowed to use WSL and docker. I would like to know whether doccano aims to support Windows or not in the newer versions. There are some new features that are really nice to have, so I wanted to upgrade the current version that I was using.
