### ISSUE TITLE
Cannot start backend service from docker image

### ISSUE THREAD

**Issue by EnzoNclt** [doccano/doccano#1376]
---------

Your Environment
---------
*   Operating System: MacOS Darwin 19.6.0
*   Python Version Used: 3.9.5
*   When you install doccano: Reinstalled it May 21th, version 1.4.0, commit 7a87d7a36efb2bfbe0aba919f91413bb091742b1
*   How did you install doccano (Heroku button etc): Docker compose

After pulling the new commit from master needed for the hotfix on Custom Http request i can't start anymore the backend service, check the following logs for more informations

backend_1   |   Applying api.0012_auto_20210514_0654...Traceback (most recent call last):
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
backend_1   |     return self.cursor.execute(sql, params)
backend_1   | psycopg2.errors.ForeignKeyViolation: insert or update on table "api_comment" violates foreign key constraint "api_comment_example_id_b67fce22_fk_api_example_id"
backend_1   | DETAIL:  Key (example_id)=(1) is not present in table "api_example".
backend_1   | 
backend_1   | 
backend_1   | The above exception was the direct cause of the following exception:
backend_1   | 
backend_1   | Traceback (most recent call last):
backend_1   |   File "/src/backend/manage.py", line 15, in <module>
backend_1   |     execute_from_command_line(sys.argv)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
backend_1   |     utility.execute()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
backend_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
backend_1   |     self.execute(*args, cmd_options)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
backend_1   |     output = self.handle(*args, options)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
backend_1   |     res = handle_func(*args, kwargs)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
backend_1   |     post_migrate_state = executor.migrate(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
backend_1   |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
backend_1   |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
backend_1   |     state = migration.apply(state, schema_editor)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
backend_1   |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 104, in database_forwards
backend_1   |     schema_editor.add_field(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 508, in add_field
backend_1   |     self.execute(sql, params)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 145, in execute
backend_1   |     cursor.execute(sql, params)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
backend_1   |     return super().execute(sql, params)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
backend_1   |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
backend_1   |     return executor(sql, params, many, context)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
backend_1   |     return self.cursor.execute(sql, params)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
backend_1   |     raise dj_exc_value.with_traceback(traceback) from exc_value
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
backend_1   |     return self.cursor.execute(sql, params)
backend_1   | django.db.utils.IntegrityError: insert or update on table "api_comment" violates foreign key constraint "api_comment_example_id_b67fce22_fk_api_example_id"
backend_1   | DETAIL:  Key (example_id)=(1) is not present in table "api_example".
backend_1 exited with code 1

Other services seems to start normally, or at least i haven't seen any further issue

**Comment by EnzoNclt** [comment]
Commit https://github.com/doccano/doccano/commit/03619a97143439378750b7d3835b54ee0fdf0ade doesn't seems to fix the bug, still here.

Do I have to clean my db before retrying ? Did I forgot to initiate smth or is this a common problem on the last commits ?

Thx in advance

**Comment by EnzoNclt** [comment]
Quick hack while commenting the concerned migration. Therefore, issue https://github.com/doccano/doccano/issues/1307 seems to reappears. For now, half fix using this modification:

> diff --git a/backend/api/migrations/0012_auto_20210514_0654.py b/backend/api/migrations/0012_auto_20210514_0654.py
> index 5d6f819e..9c6963e0 100644
> --- a/backend/api/migrations/0012_auto_20210514_0654.py
> +++ b/backend/api/migrations/0012_auto_20210514_0654.py
> @@ -185,12 +185,12 @@ class Migration(migrations.Migration):
>              name='user',
>              field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
>          ),
> -        migrations.AddField(
> -            model_name='comment',
> -            name='example',
> -            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.example'),
> -            preserve_default=False,
> -        ),
> +        # migrations.AddField(
> +        #     model_name='comment',
> +        #     name='example',
> +        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.example'),
> +        #     preserve_default=False,
> +        # ),
>          migrations.AlterUniqueTogether(
>              name='category',
>              unique_together={('example', 'user', 'label')},
> diff --git a/backend/api/views/auto_labeling.py b/backend/api/views/auto_labeling.py
> index ae660f79..3ab0c063 100644
> --- a/backend/api/views/auto_labeling.py
> +++ b/backend/api/views/auto_labeling.py
> @@ -2,7 +2,7 @@ import botocore.exceptions
>  import requests
>  from auto_labeling_pipeline.mappings import MappingTemplate
>  from auto_labeling_pipeline.menu import Options
> -from auto_labeling_pipeline.models import RequestModelFactory
> +from auto_labeling_pipeline.models import RequestModelFactory, RequestModel
>  from auto_labeling_pipeline.pipeline import pipeline
>  from auto_labeling_pipeline.postprocessing import PostProcessor
>  from auto_labeling_pipeline.task import TaskFactory
> @@ -21,6 +21,14 @@ from ..permissions import IsInProjectOrAdmin, IsProjectAdmin
>  from ..serializers import (AutoLabelingConfigSerializer,
>                             get_annotation_serializer)
>  
> +@classmethod
> +def monkey_patched_find(cls, model_name: str): #-> Type[RequestModel]:
> +        for subclass in RequestModel.__subclasses__():
> +            if subclass.Config.title == model_name:
> +                return subclass
> +        raise NameError(f'{model_name} is not found.')
> +
> +RequestModelFactory.find = monkey_patched_find
>  
>  class AutoLabelingTemplateListAPI(APIView):
>      permission_classes = [IsAuthenticated & IsProjectAdmin]
