### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by mehmetilker** [doccano/doccano#1397]
How to reproduce the behaviour
---------
-create new env on ubuntu
-install with pip with following (pip installation section)
-start in a shell with "doccano webserver --port 8000" and another shell "doccano task"
-Try to upload following line as jsonl file (changing column label to labels)
~~~
{"text":"Easily create clusters that run preconfigured open source software. Install using-facing applications like blogs or chat, or sidecars to better operate your own containers.mas","labels":[[14,28,"WORK_OF_ART"]]}
~~~

-Upload progress finish with success message but I see following error on "docanno task" shell:

~~~
[2021-06-03 10:11:49,748: ERROR/ForkPoolWorker-1] Task api.tasks.injest_data[b2cb8a44-81bc-4391-a85f-2cd19764590b] raised unexpected: TypeError("[14, 28, 'WORK_OF_ART'] is not str.")
Traceback (most recent call last):
  File "/home/projects/test-project/.env/lib/python3.8/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/projects/test-project/.env/lib/python3.8/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/projects/test-project/.env/lib/python3.8/site-packages/backend/api/tasks.py", line 111, in injest_data
    example = next(it)
  File "/home/projects/test-project/.env/lib/python3.8/site-packages/backend/api/views/upload/dataset.py", line 68, in __iter__
    yield from self.load(filename)
  File "/home/projects/test-project/.env/lib/python3.8/site-packages/backend/api/views/upload/dataset.py", line 187, in load
    yield self.from_row(filename, row, line_num)
  File "/home/projects/test-project/.env/lib/python3.8/site-packages/backend/api/views/upload/dataset.py", line 114, in from_row
    label = [self.label_class.parse(o) for o in label]
  File "/home/projects/test-project/.env/lib/python3.8/site-packages/backend/api/views/upload/dataset.py", line 114, in <listcomp>
    label = [self.label_class.parse(o) for o in label]
  File "/home/projects/test-project/.env/lib/python3.8/site-packages/backend/api/views/upload/label.py", line 98, in parse
    raise TypeError(f'{obj} is not str.')
TypeError: [14, 28, 'WORK_OF_ART'] is not str.
~~~

Your Environment
---------

*   Operating System: ubuntu 18
*   Python Version Used: 3.8
*   When you install doccano: version 1.4.1
*   How did you install doccano (Heroku button etc): pip

**Comment by Hironsan** [comment]
You are trying to upload sequence labeling data to the seq2seq project. Please create a sequence labeling project and upload your data.
