### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by therealgherkhin** [doccano/doccano#1414]
How to reproduce the behaviour
---------
After downloading doccano and trying to start it via `doccano init` I get the following message:

```
doccano init
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python39\Scripts\doccano-script.py", line 33, in <module>
    sys.exit(load_entry_point('doccano==1.4.1', 'console_scripts', 'doccano')())
  File "C:\Users\\AppData\Local\Programs\Python\Python39\Scripts\doccano-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\\appdata\local\programs\python\python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\\appdata\local\programs\python\python39\lib\site-packages\backend\cli.py", line 7, in <module>
    import gunicorn.app.base
  File "c:\users\\appdata\local\programs\python\python39\lib\site-packages\gunicorn\app\base.py", line 11, in <module>
    from gunicorn import util
  File "c:\users\\appdata\local\programs\python\python39\lib\site-packages\gunicorn\util.py", line 8, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl' 
```

Your Environment
---------
*   Operating System: Windows 10 1909
*   Python Version Used: 3.9.4
*   When you install doccano: 17.06.2021
*   How did you install doccano (Heroku button etc): `pip install doccano`

Own Research:
----------
Apparently Windows doesn''t support `fcntl`. Therefore nobody that uses Windows can install doccano via pip.

**Comment by RishiMalhotra920** [comment]
I ran into the same issue and used docker to install Doccano on windows.

**Comment by therealgherkhin** [comment]
Yes with docker everything seems fine, but I think this should be stated somewhere.

**Comment by AX0123SR** [comment]
While installing ansible in my windows, I ma getting this error "ERROR: No module named 'fcntl' ".
How to resolve this?

**Comment by therealgherkhin** [comment]
As already mentioned: Gunicorn isn't supported by windows. Try the workaround from @Hironsan above.

**Comment by therealgherkhin** [comment]
Use Docker. I think that `fcntl` still doesn't support Windows. In a Docker-Container there won't be this issue.

**Comment by AX0123SR** [comment]
Can you pls tell me exactly how can I do?

**Comment by therealgherkhin** [comment]
The installation via Docker is stated in the [README](https://github.com/doccano/doccano).
Pull the Docker-Image:
`docker pull doccano/doccano`

Create the container and choose your password, port, etc:
`docker container create --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=admin@example.com" \
  -e "ADMIN_PASSWORD=password" \
  -v doccano-db:/data \
  -p 8000:8000 doccano/doccano`

Start the container:
`docker container start doccano`

You can now find the instance under your localhost:8000
