### ISSUE TITLE
ValueError: bulk_create() prohibited to prevent data loss due to unsaved related object 'example'.

### ISSUE THREAD

**Issue by naty88** [doccano/doccano#1535]
With the latest Doccano release (v1.5.0) there is a new error by importing of the dataset both in JSON and JSONL format. The same data format works in the release v1.4.1.
For our use case the problem is that the importing itself works, but the corresponding label is not marked anymore as a label of a particular text like it was in the release  v1.4.1 (s. image "auto_label_v1 4 1.png").

Error:
```
[2021-10-27 11:24:33,982: ERROR/ForkPoolWorker-1] Task api.tasks.injest_data[6ac92f0c-558e-4ac4-aac2-739921574989] raised unexpected: ValueError("bulk_create() prohibited to prevent data loss due to unsaved related object 'example'.")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/doccano/backend/api/tasks.py", line 124, in injest_data
    factory.create(buffer.data, user, project)
  File "/doccano/backend/api/tasks.py", line 85, in create
    self.create_annotation(examples, ids, user, project)
  File "/doccano/backend/api/tasks.py", line 80, in create_annotation
    self.annotation_class.objects.bulk_create(annotation)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 498, in bulk_create
    self._prepare_for_bulk_create(objs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 461, in _prepare_for_bulk_create
    obj._prepare_related_fields_for_save(operation_name='bulk_create')
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 932, in _prepare_related_fields_for_save
    raise ValueError(
ValueError: bulk_create() prohibited to prevent data loss due to unsaved related object 'example'.
```

Environment:
*   Operating System: Ubuntu 20.04 LTS
*   Python Version Used: Python 3.8.10
*   How did you install doccano (Heroku button etc):  Doccano was deployed with [Helm-Chart ](https://github.com/curie-data-factory/helm-charts/tree/master/charts/doccano).
![auto_label_v1 4 1](https://user-images.githubusercontent.com/44298164/139059258-1320a8a6-ec15-4285-88ac-37119a102dae.png)

**Comment by Hironsan** [comment]
Thanks. I can reproduce the problem.

**Comment by Hironsan** [comment]
It seems to me that the problem is occured in https://github.com/doccano/doccano/pull/1442.
- https://github.com/doccano/doccano/pull/1442/files#diff-7a9f9d2a81f523b64e2114908bcfe7df4647107b6e56d0037aef21f77332a09bR64

In SQLite3, `bulk_create` does not return any values related to `example` so `create_annotation` method failed.

**Comment by naty88** [comment]
Thank you for answering and for fixing it.
