### ISSUE TITLE
how to upgrade 1.5.0 to 1.5.1

### ISSUE THREAD

**Issue by Shinku-Chen** [doccano/doccano#1548]
How to reproduce the problem
---------

```bash
# copy-paste the error message here
```

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

command:
/home/workuser/.local/bin/doccano init 
error:
psycopg2.errors.CannotCoerce: cannot cast type integer to uuid
LINE 1: ...E "api_example" ALTER COLUMN "id" TYPE uuid USING "id"::uuid
                                                                 ^

**Comment by EnzoNclt** [comment]
Same thing with the docker installation, i'm working with the docker development part and I have the same issue, with more log sent by the backend:
```
backend_1   |   Applying api.0017_alter_example_id...Traceback (most recent call last):
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
backend_1   |     return self.cursor.execute(sql, params)
backend_1   | psycopg2.errors.CannotCoerce: cannot cast type integer to uuid
backend_1   | LINE 1: ...E "api_example" ALTER COLUMN "id" TYPE uuid USING "id"::uuid
backend_1   |                                                                  ^
backend_1   | 
backend_1   | 
backend_1   | The above exception was the direct cause of the following exception:
backend_1   | 
backend_1   | Traceback (most recent call last):
backend_1   |   File "/src/backend/manage.py", line 15, in <module>
backend_1   |     execute_from_command_line(sys.argv)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
backend_1   |     utility.execute()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
backend_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
backend_1   |     self.execute(*args, **cmd_options)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
backend_1   |     output = self.handle(*args, **options)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
backend_1   |     res = handle_func(*args, **kwargs)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
backend_1   |     post_migrate_state = executor.migrate(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
backend_1   |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
backend_1   |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
backend_1   |     state = migration.apply(state, schema_editor)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
backend_1   |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 244, in database_forwards
backend_1   |     schema_editor.alter_field(from_model, from_field, to_field)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 608, in alter_field
backend_1   |     self._alter_field(model, old_field, new_field, old_type, new_type,
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/schema.py", line 196, in _alter_field
backend_1   |     super()._alter_field(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 765, in _alter_field
backend_1   |     self.execute(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 145, in execute
backend_1   |     cursor.execute(sql, params)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
backend_1   |     return super().execute(sql, params)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
backend_1   |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
backend_1   |     return executor(sql, params, many, context)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
backend_1   |     return self.cursor.execute(sql, params)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
backend_1   |     raise dj_exc_value.with_traceback(traceback) from exc_value
backend_1   |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
backend_1   |     return self.cursor.execute(sql, params)
backend_1   | django.db.utils.ProgrammingError: cannot cast type integer to uuid
backend_1   | LINE 1: ...E "api_example" ALTER COLUMN "id" TYPE uuid USING "id"::uuid
backend_1   |                                                                  ^
backend_1   |
```

It might me caused by this warning I've got from Celery just above:

```
celery_1    | /usr/local/lib/python3.8/site-packages/celery/platforms.py:834: SecurityWarning: You're running the worker with superuser privileges: this is
celery_1    | absolutely not recommended!
celery_1    | 
celery_1    | Please specify a different user using the --uid option.
celery_1    | 
celery_1    | User information: uid=0 euid=0 gid=0 egid=0
celery_1    | 
celery_1    |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(

```

**Comment by Shinku-Chen** [comment]
export DATABASE_URL=postgres://
database:postgres

**Comment by EnzoNclt** [comment]
This is caused by this line added in `backend/api/models.py` (l 153):
```
class Example(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, db_index=True) # This one
    meta = models.JSONField(default=dict)
    filename = models.FileField(default='.', max_length=1024)
```

I think they forgot to reapply migrations on the postgres db, which cause this error.

**Comment by EnzoNclt** [comment]
Thanks @Shinku-Chen, worked pretty well for me. For docker user this file is stored under /backend/api/migrations/. Here is the git diff:

```diff
--- a/backend/api/migrations/0012_auto_20210514_0654.py
+++ b/backend/api/migrations/0012_auto_20210514_0654.py
@@ -3,6 +3,7 @@
 from django.conf import settings
 from django.db import migrations, models
 import django.db.models.deletion
+import uuid
 
 
 class Migration(migrations.Migration):
@@ -26,7 +27,7 @@ class Migration(migrations.Migration):
         migrations.CreateModel(
             name='Example',
             fields=[
-                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
+                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                 ('meta', models.JSONField(default=dict)),
                 ('filename', models.FileField(default='.', upload_to='')),
                 ('text', models.TextField(blank=True, null=True)),
```

**Comment by Shinku-Chen** [comment]
i'm not sure whether it is useful for updating from 1.5.0 to 1.5.1 with database

0017_alter_example_id.py can't work under postgres for exist database
