### ISSUE TITLE
Better error messages when uplading dataset

### ISSUE THREAD

**Issue by Randl** [doccano/doccano#1560]
Feature description
---------
When I upload my dataset (generated elsewhere), the only error messages I get are the ones from django in console. For example, I once had a problem with metadata in one of the samples and all I got was
`django.db.utils.IntegrityError: CHECK constraint failed: api_example` in console and nothing in web interface. At least having reference to which example lead to error would be extremely helpful.

**Comment by Hironsan** [comment]
Can you show me some example data to reproduce the problem?

**Comment by Randl** [comment]
For example, trying to loading duplicated labels
```
{"text": "HI hi hi hi hi HI hi hi hi hi", "label": [[3, 5, "Type"], [3, 5, "Type"]]}
```
 results in
```
[2021-11-14 07:25:04,970: ERROR/ForkPoolWorker-2] Task api.tasks.injest_data[1d4a9e42-6baf-49a8-9e4f-1807667bb48d] raised unexpected: IntegrityError('UNIQUE constraint failed: api_span.example_id, api_span.user_id, api_span.label_id, api_span.start_offset, api_span.end_offset')
Traceback (most recent call last):
  File "/home/vista/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vista/.local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: api_span.example_id, api_span.user_id, api_span.label_id, api_span.start_offset, api_span.end_offset

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vista/.local/lib/python3.8/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/vista/.local/lib/python3.8/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/vista/.local/lib/python3.8/site-packages/backend/api/tasks.py", line 123, in injest_data
    factory.create(buffer.data, user, project)
  File "/home/vista/.local/lib/python3.8/site-packages/backend/api/tasks.py", line 85, in create
    self.create_annotation(examples, ids, user, project)
  File "/home/vista/.local/lib/python3.8/site-packages/backend/api/tasks.py", line 80, in create_annotation
    self.annotation_class.objects.bulk_create(annotation)
  File "/home/vista/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vista/.local/lib/python3.8/site-packages/django/db/models/query.py", line 514, in bulk_create
    returned_columns = self._batched_insert(
  File "/home/vista/.local/lib/python3.8/site-packages/django/db/models/query.py", line 1293, in _batched_insert
    self._insert(item, fields=fields, using=self.db, ignore_conflicts=ignore_conflicts)
  File "/home/vista/.local/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/vista/.local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/home/vista/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/vista/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/vista/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/vista/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vista/.local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vista/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vista/.local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: api_span.example_id, api_span.user_id, api_span.label_id, api_span.start_offset, api_span.end_offset
```
in console and nothing in interface. After I guessed what the problem was it was easy to fix, but it is hard to guess.
Other problems which I have no samples for currently also sometimes result in cryptic django error which can nearly impossible to decipher until you pinpoint one of possibly thousand of samples causing the problem.

**Comment by Hironsan** [comment]
Thanks.
