### ISSUE TITLE
Deploy doccano on Heroku

### ISSUE THREAD

**Issue by moltaheb** [doccano/doccano#1734]
while I using Heroku deployment button I had an issue as the following : 

[36;1mOperations to perform:[0m

[1m  Apply all migrations: [0madmin, api, auth, authtoken, auto_labeling, contenttypes, django_celery_results, django_drf_filepond, examples, label_types, labels, projects, roles, sessions

[36;1mRunning migrations:[0m

  Applying api.0015_examplestate...Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 83, in _execute

    return self.cursor.execute(sql)

psycopg2.errors.DuplicateTable: relation "api_examplestate" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/doccano/backend/manage.py", line 15, in <module>

    execute_from_command_line(sys.argv)

  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line

    utility.execute()

  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 373, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 417, in execute

    output = self.handle(*args, **options)

  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 90, in wrapped

    res = handle_func(*args, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 253, in handle

    post_migrate_state = executor.migrate(

  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 126, in migrate

    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)

  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 156, in _migrate_all_forwards

    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)

  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 236, in apply_migration

    state = migration.apply(state, schema_editor)

  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 125, in apply

    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)

  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards

    schema_editor.create_model(model)

  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 357, in create_model

    self.execute(sql, params or None)

  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 153, in execute

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 85, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 83, in _execute

    return self.cursor.execute(sql)

django.db.utils.ProgrammingError: relation "api_examplestate" already exists

**Comment by nigeltc** [comment]
I had a very similar problem with the deploy to Heroku button...
`/doccano/tools/heroku.sh: 5: /doccano/tools/heroku.sh: [[: not found
/doccano/tools/heroku.sh: 6: /doccano/tools/heroku.sh: [[: not found
/doccano/tools/heroku.sh: 7: /doccano/tools/heroku.sh: [[: not found
[36;1mOperations to perform:[0m
[1m  Apply all migrations: [0madmin, api, auth, authtoken, auto_labeling, contenttypes, data_export, data_import, django_celery_results, django_drf_filepond, examples, label_types, labels, projects, roles, sessions
[36;1mRunning migrations:[0m
  Applying projects.0004_sequencelabelingproject_use_relation...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateColumn: column "use_relation" of relation "projects_sequencelabelingproject" already exists

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/doccano/backend/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 290, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 131, in migrate
    state = self._migrate_all_forwards(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 163, in _migrate_all_forwards
    state = self.apply_migration(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 248, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 131, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 108, in database_forwards
    schema_editor.add_field(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 641, in add_field
    self.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 192, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "use_relation" of relation "projects_sequencelabelingproject" already exists`

I had filled in the email/user name/password fields

**Comment by Hironsan** [comment]
I can't reproduce the problem but `fake-initial` option may be helpful:

- [fake-initial](https://docs.djangoproject.com/en/4.0/ref/django-admin/#cmdoption-migrate-fake-initial)

**Comment by moltaheb** [comment]
what  if I give you my edited version and try to upload it from your side ?
