### ISSUE TITLE
 Unrecoverable error: AttributeError("'EntryPoint' object has no attribute 'module_name'") during doccano task process

### ISSUE THREAD

**Issue by qtoulou** [doccano/doccano#1768]
How to reproduce the problem
---------

When I try to install doccano, I have an error when I launch the following command : `doccano task`
I don't have any error during the previous install stages (pip install, doccano init, doccano createuser, doccano webserver)

```bash
[2022-04-04 10:15:06,202: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'EntryPoint' object has no attribute 'module_name'")
```

As the doccano webserver command works, I can go through the UI but I got the same error in the logs when I'm trying to import a dataset for example. 

Full traceback : 

```
❯ doccano task
Starting task queue.

[2022-04-04 10:24:25,001: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'EntryPoint' object has no attribute 'module_name'")
Traceback (most recent call last):
  File "/Users/XXX/opt/anaconda3/lib/python3.8/site-packages/celery/app/base.py", line 1250, in backend
    return self._local.backend
AttributeError: '_thread._local' object has no attribute 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/XXX/opt/anaconda3/lib/python3.8/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/Users/XXX/opt/anaconda3/lib/python3.8/site-packages/celery/bootsteps.py", line 112, in start
    self.on_start()
  File "/Users/XXX/opt/anaconda3/lib/python3.8/site-packages/celery/apps/worker.py", line 136, in on_start
    self.emit_banner()
  File "/Users/XXX/opt/anaconda3/lib/python3.8/site-packages/celery/apps/worker.py", line 170, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/Users/XXX/opt/anaconda3/lib/python3.8/site-packages/celery/apps/worker.py", line 232, in startup_info
    results=self.app.backend.as_uri(),
  File "/Users/XXX/opt/anaconda3/lib/python3.8/site-packages/celery/app/base.py", line 1252, in backend
    self._local.backend = new_backend = self._get_backend()
  File "/Users/XXX/opt/anaconda3/lib/python3.8/site-packages/celery/app/base.py", line 955, in _get_backend
    backend, url = backends.by_url(
  File "/Users/XXX/opt/anaconda3/lib/python3.8/site-packages/celery/app/backends.py", line 69, in by_url
    return by_name(backend, loader), url
  File "/Users/XXX/opt/anaconda3/lib/python3.8/site-packages/celery/app/backends.py", line 47, in by_name
    aliases.update(load_extension_class_names(extension_namespace))
  File "/Users/XXX/opt/anaconda3/lib/python3.8/site-packages/celery/utils/imports.py", line 146, in load_extension_class_names
    yield ep.name, ':'.join([ep.module_name, ep.attrs[0]])
AttributeError: 'EntryPoint' object has no attribute 'module_name'
```

Your Environment
---------

*   Operating System: macOS (M1)
*   Python Version Used: 3.8.12
*   How did you install doccano (Heroku button etc): pip install

**Comment by Hironsan** [comment]
Could you please tell me which version you installed?

```bash
pip freeze | grep doccano
```

**Comment by qtoulou** [comment]
This is the last version : 1.6.2 

```
❯ pip freeze | grep doccano
doccano==1.6.2
```

**Comment by Hironsan** [comment]
Thanks. I try to reproduce the problem.

**Comment by rhildebrandfive** [comment]
Same issue here.

macOS (M1)
Python 3.9.10
