### ISSUE TITLE
Error during `doccano init`

### ISSUE THREAD

**Issue by takana-v** [doccano/doccano#1792]
How to reproduce the problem
---------

I get an error when installing using pip with python 3.8 on windows.

```bash
> doccano init
Filepond app init: Creating temporary file upload directory <c:\users\takana\documents\works\doccano\venv\lib\site-packages\backend\filepond-temp-uploads>
Filepond app init: Creating file store directory <C:\Users\takana/doccano\media>...
Setup Database.
Operations to perform:
  Apply all migrations: admin, api, auth, authtoken, auto_labeling, contenttypes, django_celery_results, django_drf_filepond, examples, label_types, labels, projects, roles, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying api.0001_initial... OK
  Applying api.0002_speech2text... OK
  Applying api.0002_project_single_class_classification... OK
  Applying api.0003_merge_20200612_0205... OK
  Applying api.0002_comment... OK
  Applying api.0004_merge_20210114_1117... OK
  Applying api.0005_auto_20210201_0603...Traceback (most recent call last):
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\db\backends\utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 475, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: no such function: JSON_VALID

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\takana\.pyenv\pyenv-win\versions\3.8.10\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\takana\.pyenv\pyenv-win\versions\3.8.10\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\takana\Documents\works\doccano\venv\Scripts\doccano.exe\__main__.py", line 7, in <module>
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\backend\cli.py", line 153, in main
    args.handler(args)
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\backend\cli.py", line 73, in command_db_init
    management.call_command("migrate")
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\core\management\__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\core\management\base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\core\management\base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\core\management\commands\migrate.py", line 290, in handle
    post_migrate_state = executor.migrate(
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\db\migrations\executor.py", line 131, in migrate
    state = self._migrate_all_forwards(
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\db\migrations\executor.py", line 163, in _migrate_all_forwards
    state = self.apply_migration(
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\db\migrations\executor.py", line 248, in apply_migration
    state = migration.apply(state, schema_editor)
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\db\migrations\migration.py", line 131, in apply
    operation.database_forwards(
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\db\migrations\operations\models.py", line 93, in database_forwards
    schema_editor.create_model(model)
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\db\backends\base\schema.py", line 432, in create_model
    self.execute(sql, params or None)
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\db\backends\base\schema.py", line 192, in execute
    cursor.execute(sql, params)
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\db\backends\utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "c:\users\takana\documents\works\doccano\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 475, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: no such function: JSON_VALID
```

Your Environment
---------

*   Operating System: Windows
*   Python Version Used: 3.8.10
*   When you install doccano: 2022/04/21 (doccano==1.6.2)
*   How did you install doccano (Heroku button etc): pip

**Comment by takana-v** [comment]
The JSON1 extension is not enabled by default in Python 3.8 on Windows.
https://code.djangoproject.com/wiki/JSON1Extension#windows
