### ISSUE TITLE
ModuleNotFoundError: No module named 'examples.models'

### ISSUE THREAD

**Issue by skaistt** [doccano/doccano#1796]
After I installed doccano with pip, I cannot run any doccano commands, such as 'doccano init'. Not sure what's an issue here..
Installation was successful (`Successfully installed doccano-1.6.2`)

```bash
Traceback (most recent call last):
  File "/home/xv885ju/python/.venv/bin/doccano", line 5, in <module>
    from backend.cli import main
  File "/home/xv885ju/python/.venv/lib/python3.8/site-packages/backend/cli.py", line 21, in <module>
    django.setup()
  File "/home/xv885ju/python/.venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/xv885ju/python/.venv/lib/python3.8/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/xv885ju/python/.venv/lib/python3.8/site-packages/django/apps/config.py", line 304, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/xv885ju/python/.venv/lib/python3.8/site-packages/backend/labels/models.py", line 12, in <module>
    from examples.models import Example
ModuleNotFoundError: No module named 'examples.models'
```

Your Environment
---------

*   Operating System: Ubuntu 20.04.3 LTS
*   Python Version Used: 3.8.10
*   When you install doccano: 22.04.2022
*   How did you install doccano (Heroku button etc): pip

**Comment by giadasp** [comment]
I encounter the same error. Please help!

**Comment by bfsujason** [comment]
The following steps works for me (Windows 10):

1. Use command line to change to the path
    your/path/to/python/site-packages/backend

2. Run 
    doccano init

**Comment by skaistt** [comment]
@bfsujason Thanks, it worked!

**Comment by Hironsan** [comment]
duplicate to #1768

**Comment by chengyjonathan** [comment]
I'm also running into this

**Comment by Hel5ing** [comment]
Python 3.9.16
MacBook Apple M1 Ventura

Also face this issue

**Comment by jiaohuix** [comment]
> 1. site-packages

It worked, my environment is windows, use cd C:\Users\USER_NAME\AppData\Local\Programs\Python\Python311\Lib\site-packages\backend
Then doccano init。  thanks！
