### ISSUE TITLE
Error in Initialize database step after doccano init

### ISSUE THREAD

**Issue by alemol** [doccano/doccano#1807]
I got this problem after the "Initialize database" command:

**django.db.utils.NotSupportedError: Renaming the 'api_role' table while in a transaction is not supported on SQLite < 3.26 because it would break referential integrity. Try adding `atomic = False` to the Migration class.**

---------

```bash
$virtualenv --python=python3 venv
$source venv/bin/activate
(venv) $python --version
Python 3.8.0
(venv) $pip3 install doccano
$doccano init
  Applying api.0028_auto_20220111_0655...Traceback (most recent call last):
  File "/Volumes/LiteHD/amolina/repo/annot/venv/bin/doccano", line 8, in <module>
    sys.exit(main())
  File "/Volumes/LiteHD/amolina/repo/annot/venv/lib/python3.8/site-packages/backend/cli.py", line 153, in main
    args.handler(args)
  File "/Volumes/LiteHD/amolina/repo/annot/venv/lib/python3.8/site-packages/backend/cli.py", line 73, in command_db_init
    management.call_command("migrate")
  File "/Volumes/LiteHD/amolina/repo/annot/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
  File "/Volumes/LiteHD/amolina/repo/annot/venv/lib/python3.8/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/Volumes/LiteHD/amolina/repo/annot/venv/lib/python3.8/site-packages/django/core/management/base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Volumes/LiteHD/amolina/repo/annot/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 290, in handle
    post_migrate_state = executor.migrate(
  File "/Volumes/LiteHD/amolina/repo/annot/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 131, in migrate
    state = self._migrate_all_forwards(
  File "/Volumes/LiteHD/amolina/repo/annot/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 163, in _migrate_all_forwards
    state = self.apply_migration(
  File "/Volumes/LiteHD/amolina/repo/annot/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 248, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Volumes/LiteHD/amolina/repo/annot/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 131, in apply
    operation.database_forwards(
  File "/Volumes/LiteHD/amolina/repo/annot/venv/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 37, in database_forwards
    database_operation.database_forwards(
  File "/Volumes/LiteHD/amolina/repo/annot/venv/lib/python3.8/site-packages/django/db/migrations/operations/models.py", line 486, in database_forwards
    schema_editor.alter_db_table(
  File "/Volumes/LiteHD/amolina/repo/annot/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/schema.py", line 107, in alter_db_table
    raise NotSupportedError(
django.db.utils.NotSupportedError: Renaming the 'api_role' table while in a transaction is not supported on SQLite < 3.26 because it would break referential integrity. Try adding `atomic = False` to the Migration class.

```

Your Environment
---------

*   Operating System: OS X 10.15.7 (Catalina)
*   Python Version Used: 3.8 (virtualenv)
*   When you install doccano: 28/04/2022
*   How did you install doccano (Heroku button etc): pip install doccano

**Comment by cjj1472111531** [comment]
你解决了？

**Comment by Hironsan** [comment]
I can't reproduce the problem:
- Python version: 3.8.14
- Sqlite3 version: 3.25.2
- doccano version: 1.6.2
- Debian GNU/Linux 11 (bullseye)
