### ISSUE TITLE
doccano task

### ISSUE THREAD

**Issue by cjj1472111531** [doccano/doccano#1834]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by cjj1472111531** [comment]
Traceback (most recent call last):
  File "D:\code_software\Anaconda\envs\docc\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\code_software\Anaconda\envs\docc\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\code_software\Anaconda\envs\docc\Scripts\doccano.exe\__main__.py", line 7, in <module>
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\backend\cli.py", line 160, in main
    args.handler(args)
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\backend\cli.py", line 110, in command_run_task_queue
    app.worker_main(argv=argv)
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\celery\app\base.py", line 391, in worker_main
    self.start(argv=argv)
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\celery\app\base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
  File "C:\Users\14721\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\14721\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\14721\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\14721\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\14721\AppData\Roaming\Python\Python39\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\celery\bin\base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\celery\bin\worker.py", line 343, in worker
    worker = app.Worker(
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\celery\worker\worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\celery\loaders\base.py", line 111, in init_worker
    self.import_default_modules()
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\celery\loaders\base.py", line 105, in import_default_modules
    raise response
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\celery\utils\dispatch\signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\celery\fixups\django.py", line 82, in on_import_modules
    self.worker_fixup.validate_models()
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\celery\fixups\django.py", line 121, in validate_models
    run_checks()
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    return check_method()
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\django\urls\resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\django\utils\functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\django\urls\resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\django\utils\functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\django\urls\resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "D:\code_software\Anaconda\envs\docc\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\backend\config\urls.py", line 58, in <module>
    path("v1/projects/<int:project_id>/metrics/", include("metrics.urls")),
  File "D:\code_software\Anaconda\envs\docc\lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\code_software\Anaconda\envs\docc\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'metrics.urls'

**Comment by Hironsan** [comment]
duplicate to #1768
