### ISSUE TITLE
doccano init Applying django_celery_results.0007_remove_taskresult_hidden...Traceback

### ISSUE THREAD

**Issue by yishen-zhao** [doccano/doccano#1932]
How to reproduce the problem
---------

doccano init
```bash
# copy-paste the error message here
```
doccano init
Setup Database.
Operations to perform:
  Apply all migrations: admin, api, auth, authtoken, auto_labeling, contenttypes, data_export, data_import, django_celery_results, django_drf_filepond, examples, label_types, labels, projects, roles, sessions
Running migrations:
  Applying django_celery_results.0007_remove_taskresult_hidden...Traceback (most recent call last):
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: error in index django_celery_results_taskresult_hidden_cd77412f after drop column: no such column: hidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/11121901/data/anaconda3/envs/Py38/bin/doccano", line 8, in <module>
    sys.exit(main())
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/backend/cli.py", line 160, in main
    args.handler(args)
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/backend/cli.py", line 75, in command_db_init
    management.call_command("migrate")
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/db/migrations/migration.py", line 130, in apply
    operation.database_forwards(
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 170, in database_forwards
    schema_editor.remove_field(
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/db/backends/sqlite3/schema.py", line 417, in remove_field
    super().remove_field(model, field)
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 720, in remove_field
    self.execute(sql)
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/11121901/data/anaconda3/envs/Py38/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: error in index django_celery_results_taskresult_hidden_cd77412f after drop column: no such column: hidden
Your Environment
---------

*   Operating System: centos7
*   Python Version Used: python3.8+
*   When you install doccano: init
*   How did you install doccano (Heroku button etc): pip install doccano

**Comment by lan2720** [comment]
The same error. Did you solve it?

**Comment by JiehangXie** [comment]
The same error. Did you solve it?

**Comment by littlestar502** [comment]
same issue, did you find any solution? hope the answer, thanks very much!

**Comment by cicijohn1983** [comment]
The same error. Did you solve it?

**Comment by cicijohn1983** [comment]
I solve it,
pip uninstall Django
pip install Django==4.0.4

**Comment by r-k-jonynas** [comment]
> I solve it, pip uninstall Django pip install Django==4.0.4
Fixed the issue for me, too

**Comment by CharizardAcademy** [comment]
> I solve it, pip uninstall Django pip install Django==4.0.4

thank you John, it works like a charm.

**Comment by JiehangXie** [comment]
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "doccano/doccano"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月9日(星期二) 下午2:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [doccano/doccano] doccano init Applying django_celery_results.0007_remove_taskresult_hidden...Traceback (Issue #1932)





 
I solve it,
 pip uninstall Django
 pip install Django==4.0.4
