### ISSUE TITLE
Installation using mysql

### ISSUE THREAD

**Issue by SemGa92** [doccano/doccano#1998]
Hello, 

thank you for the great work on doccano project!

From documentation:  **_"You can also use other database systems like PostgreSQL, MySQL, and so on"_** but I don't find anywhere a guide, as written for Postegre, about how I can init doccano with mysql instead of sqlite.

If there is a way to easily activate it, can you leave it in the comments? Thank you.

Meanwhile, I am trying to configure it by myself but I keep getting the same error..

How to reproduce the problem
---------
```bash
pip install mysqlclient==2.1.1
pip install doccano==1.8.0
export DATABASE_URL="mysql://username:password@host:port/db_name"
doccano init
```

```bash
Setup Database.
Operations to perform:
  Apply all migrations: admin, api, auth, authtoken, auto_labeling, contenttypes, data_export, data_import, django_celery_results, django_drf_filepond, examples, label_types, labels, projects, roles, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying api.0001_initial... OK
  Applying api.0002_speech2text... OK
  Applying api.0002_project_single_class_classification... OK
  Applying api.0003_merge_20200612_0205... OK
  Applying api.0002_comment... OK
  Applying api.0004_merge_20210114_1117... OK
  Applying api.0005_auto_20210201_0603... OK
  Applying api.0005_auto_20210120_1730... OK
  Applying api.0006_merge_20210221_1258... OK
  Applying api.0007_auto_20210301_0302... OK
  Applying api.0008_auto_20210302_1013... OK
  Applying api.0009_auto_20210411_2330... OK
  Applying api.0010_auto_20210413_0249... OK
  Applying api.0009_tag... OK
  Applying api.0011_merge_0009_tag_0010_auto_20210413_0249... OK
  Applying api.0012_auto_20210514_0654...Traceback (most recent call last):
  File "/home/samuele/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/samuele/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/samuele/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/samuele/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/samuele/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1170, "BLOB/TEXT column 'text' used in key specification without a key length")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/samuele/.local/bin/doccano", line 8, in <module>
    sys.exit(main())
  File "/home/samuele/.local/lib/python3.10/site-packages/backend/cli.py", line 160, in main
    args.handler(args)
  File "/home/samuele/.local/lib/python3.10/site-packages/backend/cli.py", line 75, in command_db_init
    management.call_command("migrate")
  File "/home/samuele/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
  File "/home/samuele/.local/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/home/samuele/.local/lib/python3.10/site-packages/django/core/management/base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/samuele/.local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 290, in handle
    post_migrate_state = executor.migrate(
  File "/home/samuele/.local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 131, in migrate
    state = self._migrate_all_forwards(
  File "/home/samuele/.local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 163, in _migrate_all_forwards
    state = self.apply_migration(
  File "/home/samuele/.local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    with self.connection.schema_editor(
  File "/home/samuele/.local/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 157, in __exit__
    self.execute(sql)
  File "/home/samuele/.local/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 192, in execute
    cursor.execute(sql, params)
  File "/home/samuele/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/samuele/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/samuele/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/samuele/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/samuele/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/samuele/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/samuele/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/samuele/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/samuele/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'text' used in key specification without a key length")

```
I thought that there was something wrong with my local configuration, so I tried the same approach inside docker container.
By default, doccano/doccano image seems not to support mysqlclient, so I have modified a little the Dockerfile installing **default-libmysqlclient-dev** at system level and **mysqlclient==2.1.1** at pip level. But running the container I still get the same error...

```bash
docker container create --name doccano   \
-e "ADMIN_USERNAME=admin"  \
-e "ADMIN_EMAIL=admin@example.com"  \
-e "ADMIN_PASSWORD=password"  \
-e "DATABASE_URL=mysql://username:password@host:port/db_name"  \
-p 8000:8000 doccano

docker container start doccano
```

```bash
Making staticfiles
Initializing database
Operations to perform:
  Apply all migrations: admin, api, auth, authtoken, auto_labeling, contenttypes, data_export, data_import, django_celery_results, django_drf_filepond, examples, label_types, labels, projects, roles, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying api.0001_initial... OK
  Applying api.0002_speech2text... OK
  Applying api.0002_project_single_class_classification... OK
  Applying api.0003_merge_20200612_0205... OK
  Applying api.0002_comment... OK
  Applying api.0004_merge_20210114_1117... OK
  Applying api.0005_auto_20210201_0603... OK
  Applying api.0005_auto_20210120_1730... OK
  Applying api.0006_merge_20210221_1258... OK
  Applying api.0007_auto_20210301_0302... OK
  Applying api.0008_auto_20210302_1013... OK
  Applying api.0009_auto_20210411_2330... OK
  Applying api.0010_auto_20210413_0249... OK
  Applying api.0009_tag... OK
  Applying api.0011_merge_0009_tag_0010_auto_20210413_0249... OK
System check identified some issues:

WARNINGS:
labels.BoundingBox: (models.W027) MySQL does not support check constraints.
	HINT: A constraint won't be created. Silence this warning if you don't care about it.
labels.Span: (models.W027) MySQL does not support check constraints.
	HINT: A constraint won't be created. Silence this warning if you don't care about it.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1170, "BLOB/TEXT column 'text' used in key specification without a key length")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 290, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 131, in migrate
    state = self._migrate_all_forwards(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 163, in _migrate_all_forwards
    state = self.apply_migration(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 251, in apply_migration
    migration_recorded = True
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 157, in __exit__
    self.execute(sql)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 192, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'text' used in key specification without a key length")

```
The final purpose is to deploy doccano on Kubernetes, but from the issues I cannot find a solution to let doccano work with mysql as expected.

Your Environment
---------

*   Operating System: Ubuntu 22.04
*   local Mysql version: 5.7, 8
*   local pip version: 22.0.2
*   local python version: 3.10.4
*   How did you install doccano: pip and docker

**Comment by Hironsan** [comment]
Thank you for the information. First, I'll try to reproduce the problem.

**Comment by Hironsan** [comment]
OK. I can reproduce the problem.

Run MySQL container:

```bash
docker run --name mysql \
 -e MYSQL_ROOT_PASSWORD=my-secret-pw \
 -e MYSQL_DATABASE=doccano \
 -e MYSQL_USER=admin \
 -e MYSQL_PASSWORD=password \
 -p 3306:3306 \
 -d mysql:8.0.30
```

Set `DATABASE_URL`:

```bash
export DATABASE_URL="mysql://admin:password@0.0.0.0:3306/doccano"
```

Setup mysqlclient:

```bash
brew install mysql-client
export PATH="/usr/local/opt/mysql-client/bin:$PATH"
pip install mysqlclient
````

Install doccano and run `init` command:

```bash
pip install doccano
doccano init
```

**Comment by qianrenjian** [comment]
![Image](https://github.com/user-attachments/assets/39017383-f1e8-41e5-9350-e8022527d353)

![Image](https://github.com/user-attachments/assets/059dca43-c4b6-4da4-87cc-fd5e62391c04)1、将所有文件中apps的default_auto_field = "django.db.models.BigAutoField"修改为default_auto_field = "django.db.models.AutoField"。2、将所有的backend文件夹中BigAutoField修改为“IntegerField” 3、doccano init 执行成功。

![Image](https://github.com/user-attachments/assets/4b6320b2-0495-4fcc-ae6e-0a6e140b7713)
