### ISSUE TITLE
Errors when excuting "Doccano init "

### ISSUE THREAD

**Issue by ItGirls** [doccano/doccano#2012]
When I excute "doccano init", I meet the following Errors:

sqlite3.OperationalError: no such table: projects_project
...
django.db.utils.OperationalError: no such table: projects_project

`
➜  ~ doccano init                                        
Setup Database.
Operations to perform:
  Apply all migrations: admin, api, auth, authtoken, auto_labeling, contenttypes, data_export, data_import, django_celery_results, django_drf_filepond, examples, label_types, labels, projects, roles, sessions
Running migrations:
  Applying examples.0002_alter_example_project...Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 355, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: no such table: projects_project

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xxx/.local/bin/doccano", line 8, in <module>
    sys.exit(main())
  File "/home/xxx/.local/lib/python3.8/site-packages/backend/cli.py", line 160, in main
    args.handler(args)
  File "/home/xxx/.local/lib/python3.8/site-packages/backend/cli.py", line 75, in command_db_init
    management.call_command("migrate")
  File "/home/xxx/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
  File "/home/xxx/.local/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/home/xxx/.local/lib/python3.8/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
  File "/home/xxx/.local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/home/xxx/.local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/home/xxx/.local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 255, in apply_migration
    migration_recorded = True
  File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/sqlite3/schema.py", line 39, in __exit__
    self.connection.check_constraints()
  File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 293, in check_constraints
    cursor.execute(
  File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/xxx/.local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 355, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: no such table: projects_project

`
My Environment

*   Operating System: Ubutu 16.04
*   Python Version Used: Python3.8.6
*  Doccano Version: 1.8.0
*   How did you install doccano (Heroku button etc): pip install doccano
*  Sqlite3 version: 3.11.0 

`➜  ~ python3.8
Python 3.8.6 (default, Sep 26 2022, 15:24:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.version
'2.6.0'
>>> sqlite3.sqlite_version
'3.11.0'
`

**Comment by ItGirls** [comment]
> When I excute "doccano init", I meet the following Errors:
> 
> sqlite3.OperationalError: no such table: projects_project ... django.db.utils.OperationalError: no such table: projects_project
> 
> ```
> ➜  ~ doccano init                                        
> Setup Database.
> Operations to perform:
>   Apply all migrations: admin, api, auth, authtoken, auto_labeling, contenttypes, data_export, data_import, django_celery_results, django_drf_filepond, examples, label_types, labels, projects, roles, sessions
> Running migrations:
>   Applying examples.0002_alter_example_project...Traceback (most recent call last):
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 87, in _execute
>     return self.cursor.execute(sql)
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 355, in execute
>     return Database.Cursor.execute(self, query)
> sqlite3.OperationalError: no such table: projects_project
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/xxx/.local/bin/doccano", line 8, in <module>
>     sys.exit(main())
>   File "/home/xxx/.local/lib/python3.8/site-packages/backend/cli.py", line 160, in main
>     args.handler(args)
>   File "/home/xxx/.local/lib/python3.8/site-packages/backend/cli.py", line 75, in command_db_init
>     management.call_command("migrate")
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 198, in call_command
>     return command.execute(*args, **defaults)
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute
>     output = self.handle(*args, **options)
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/core/management/base.py", line 96, in wrapped
>     res = handle_func(*args, **kwargs)
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 349, in handle
>     post_migrate_state = executor.migrate(
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 135, in migrate
>     state = self._migrate_all_forwards(
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
>     state = self.apply_migration(
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 255, in apply_migration
>     migration_recorded = True
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/sqlite3/schema.py", line 39, in __exit__
>     self.connection.check_constraints()
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 293, in check_constraints
>     cursor.execute(
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
>     return self._execute_with_wrappers(
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
>     return executor(sql, params, many, context)
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
>     return self.cursor.execute(sql, params)
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 87, in _execute
>     return self.cursor.execute(sql)
>   File "/home/xxx/.local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 355, in execute
>     return Database.Cursor.execute(self, query)
> django.db.utils.OperationalError: no such table: projects_project
> ```
> 
> ```
> ➜  ~ python3.8
> Python 3.8.6 (default, Sep 26 2022, 15:24:14) 
> [GCC 5.4.0 20160609] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import sqlite3
> >>> sqlite3.version
> '2.6.0'
> >>> sqlite3.sqlite_version
> '3.11.0'
> ```
> 
> My Environment
> 
>     * Operating System: Ubutu 16.04
> 
>     * Python Version Used: Python3.8.6
> 
>     * Doccano Version: 1.8.0
> 
>     * How did you install doccano (Heroku button etc): pip install doccano
> 
>     * Sqlite3 version: 3.11.0
 I fixed such erros by updating sqlite. After sqlite updated, I still faced some other errors when excute "doccano task", and I fixed by install some package and recompile python3.8.
