### ISSUE TITLE
import dataset error

### ISSUE THREAD

**Issue by May-Sunshine** [doccano/doccano#2071]
[2022-11-30 10:00:47,639: INFO/MainProcess] Task data_import.celery_tasks.import_dataset[8f3dbfd0-5f6d-4994-908d-5d1a34dd03ee] received
[2022-11-30 10:00:47,652: ERROR/MainProcess] Task data_import.celery_tasks.import_dataset[8f3dbfd0-5f6d-4994-908d-5d1a34dd03ee] raised unexpected: IntegrityError('NOT NULL constraint failed: examples_example.score')
Traceback (most recent call last):
  File "D:\Anaconda3\envs\doccano\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Anaconda3\envs\doccano\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: examples_example.score

**Comment by May-Sunshine** [comment]
Operating System: Windows 10 Pro
Python Version: 3.9.13
doccano: 1.8.0

> Would you write your environment? Thank you!

**Comment by wyhzzz** [comment]
I have the same problem:
[tasks]
  . data_export.celery_tasks.export_dataset
  . data_import.celery_tasks.import_dataset
  . health_check.contrib.celery.tasks.add

[2022-11-30 11:00:20,819: INFO/MainProcess] Connected to sqla+sqlite:///C:\Users\DELL/doccano\db.sqlite3
[2022-11-30 11:00:20,841: INFO/MainProcess] celery@DESKTOP-A764T47 ready.
[2022-11-30 11:01:33,882: INFO/MainProcess] Task data_import.celery_tasks.import_dataset[3ce1022e-50ca-47b6-8e15-8a3ba941801a] received
[2022-11-30 11:01:33,929: ERROR/MainProcess] Task data_import.celery_tasks.import_dataset[3ce1022e-50ca-47b6-8e15-8a3ba941801a] raised unexpected: IntegrityError('NOT NULL constraint failed: examples_example.score')
Traceback (most recent call last):
  File "d:\dre\dre\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "d:\dre\dre\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: examples_example.score

**Comment by May-Sunshine** [comment]
I solved this problem.
Delete the file folder "C:\Users\xxx\doccano", and then try "doccano init; doccano createuser"

**Comment by newhg** [comment]
> I solved this problem. Delete the file folder "C:\Users\xxx\doccano", and then try "doccano init; doccano createuser
Thank you, it works. But when try "doccano init", you need to save a copy of data if you had labeled data.
