### ISSUE TITLE
在“doccano task”后遇到的问题

### ISSUE THREAD

**Issue by xiaohouziaichi** [doccano/doccano#2086]
在“doccano task”后，遇到报错
如下：
Traceback (most recent call last):
  File "d:\py39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\py39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\py39\Scripts\doccano.exe\__main__.py", line 7, in <module>
  File "d:\py39\lib\site-packages\backend\cli.py", line 174, in main
    env.read_env(args.env_file, recurse=False, override=True)
  File "d:\py39\lib\site-packages\environs\__init__.py", line 409, in read_env
    raise ValueError("path must be a filename, not a directory.")
ValueError: path must be a filename, not a directory.

但是能正常登录，但是无法上传数据

Your Environment
---------

*   Operating System:
*   Python Version Used:Python3.9.6
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by xiaohouziaichi** [comment]
Windows操作系统
