### ISSUE TITLE
Task RUN ERROR when update v1.8.3 from v1.8.0

### ISSUE THREAD

**Issue by the-butterfly** [doccano/doccano#2139]
```
AppData\Roaming\Python\Python39\Scripts\doccano.exe task
[2023-02-24 11:32:30 +0800] [38172] [INFO] [django_drf_filepond.apps::ready::61] App init: no django-storages backend configured, using default (local) storage backend if set, otherwise you need to manage file storage independently of this app.
Starting task queue.
[2023-02-24 11:32:32 +0800] [38172] [INFO] [numexpr.utils::_init_num_threads::159] NumExpr defaulting to 8 threads.

 -------------- celery@DESKTOP-QIUM0DH v5.2.7 (dawn-chorus)
--- ***** -----
-- ******* ---- Windows-10-10.0.19044-SP0 2023-02-24 11:32:33
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         config:0x17b1f3f0ee0
- ** ---------- .> transport:   sqla+sqlite:///C:\Users\xxxx/doccano\db.sqlite3
- ** ---------- .> results:
- *** --- * --- .> concurrency: 2 (solo)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery


[tasks]
  . data_export.celery_tasks.export_dataset
  . data_import.celery_tasks.import_dataset
  . health_check.contrib.celery.tasks.add

[2023-02-24 11:32:33,770: INFO/MainProcess] Connected to sqla+sqlite:///C:\Users\xxxx/doccano\db.sqlite3
[2023-02-24 11:32:33,788: INFO/MainProcess] celery@DESKTOP-QIUM0DH ready.
[2023-02-24 11:32:33,798: INFO/MainProcess] Task data_import.celery_tasks.import_dataset[1802c2f8-b580-40bb-8d24-548d2f7824d8] received
[2023-02-24 11:32:33,822: WARNING/MainProcess] C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\app\trace.py:660: RuntimeWarning: Exception raised outside body: OperationalError('no such column: django_celery_results_taskresult.periodic_task_name'):
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: django_celery_results_taskresult.periodic_task_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\app\trace.py", line 518, in trace_task
    task.backend.mark_as_done(
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\backends\base.py", line 162, in mark_as_done
    self.store_result(task_id, result, state, request=request)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\backends\base.py", line 528, in store_result
    self._store_result(task_id, result, state, traceback,
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django_celery_results\backends\database.py", line 132, in _store_result
    self.TaskModel._default_manager.store_result(**task_props)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django_celery_results\managers.py", line 43, in _inner
    return fun(*args, **kwargs)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django_celery_results\managers.py", line 168, in store_result
    obj, created = self.using(using).get_or_create(task_id=task_id,
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 646, in get
    num = len(clone)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\sql\compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: django_celery_results_taskresult.periodic_task_name

  warn(RuntimeWarning(

[2023-02-24 11:32:33,828: CRITICAL/MainProcess] Unrecoverable error: OperationalError('no such column: django_celery_results_taskresult.periodic_task_name')
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: django_celery_results_taskresult.periodic_task_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\app\trace.py", line 518, in trace_task
    task.backend.mark_as_done(
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\backends\base.py", line 162, in mark_as_done
    self.store_result(task_id, result, state, request=request)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\backends\base.py", line 528, in store_result
    self._store_result(task_id, result, state, traceback,
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django_celery_results\backends\database.py", line 132, in _store_result
    self.TaskModel._default_manager.store_result(**task_props)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django_celery_results\managers.py", line 43, in _inner
    return fun(*args, **kwargs)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django_celery_results\managers.py", line 168, in store_result
    obj, created = self.using(using).get_or_create(task_id=task_id,
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 646, in get
    num = len(clone)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\sql\compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: django_celery_results_taskresult.periodic_task_name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: django_celery_results_taskresult.periodic_task_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\worker\worker.py", line 203, in start
    self.blueprint.start(self)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\bootsteps.py", line 116, in start
    step.start(parent)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\bootsteps.py", line 365, in start
    return self.obj.start()
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\worker\consumer\consumer.py", line 332, in start
    blueprint.start(self)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\bootsteps.py", line 116, in start
    step.start(parent)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\worker\consumer\consumer.py", line 628, in start
    c.loop(*c.loop_args())
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\worker\loops.py", line 130, in synloop
    connection.drain_events(timeout=2.0)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\kombu\connection.py", line 316, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\kombu\transport\virtual\base.py", line 971, in drain_events
    get(self._deliver, timeout=timeout)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\kombu\utils\scheduling.py", line 52, in get
    return self.fun(resource, callback, **kwargs)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\kombu\transport\virtual\base.py", line 1009, in _drain_channel
    return channel.drain_events(callback=callback, timeout=timeout)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\kombu\transport\virtual\base.py", line 736, in drain_events
    return self._poll(self.cycle, callback, timeout=timeout)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\kombu\transport\virtual\base.py", line 400, in _poll
    return cycle.get(callback)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\kombu\utils\scheduling.py", line 52, in get
    return self.fun(resource, callback, **kwargs)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\kombu\transport\virtual\base.py", line 404, in _get_and_deliver
    callback(message, queue)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\kombu\transport\virtual\base.py", line 991, in _deliver
    callback(message)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\kombu\transport\virtual\base.py", line 624, in _callback
    return callback(message)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\kombu\messaging.py", line 626, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\worker\consumer\consumer.py", line 596, in on_task_received
    strategy(
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\worker\strategy.py", line 207, in task_message_handler
    handle(req)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\worker\worker.py", line 226, in _process_task
    req.execute_using_pool(self.pool)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\worker\request.py", line 707, in execute_using_pool
    result = apply_async(
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\concurrency\base.py", line 152, in apply_async
    return self.on_apply(target, args, kwargs,
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\concurrency\base.py", line 29, in apply_target
    ret = target(*args, **kwargs)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\app\trace.py", line 649, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\app\trace.py", line 572, in trace_task
    I, _, _, _ = on_error(task_request, exc, uuid)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\app\trace.py", line 379, in on_error
    R = I.handle_error_state(
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\app\trace.py", line 178, in handle_error_state
    return {
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\app\trace.py", line 225, in handle_failure
    task.backend.mark_as_failure(
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\backends\base.py", line 172, in mark_as_failure
    self.store_result(task_id, exc, state,
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\celery\backends\base.py", line 528, in store_result
    self._store_result(task_id, result, state, traceback,
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django_celery_results\backends\database.py", line 132, in _store_result
    self.TaskModel._default_manager.store_result(**task_props)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django_celery_results\managers.py", line 43, in _inner
    return fun(*args, **kwargs)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django_celery_results\managers.py", line 168, in store_result
    obj, created = self.using(using).get_or_create(task_id=task_id,
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 928, in get_or_create
    return self.get(**kwargs), False
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 646, in get
    num = len(clone)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\models\sql\compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\xxxx\AppData\Roaming\Python\Python39\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: django_celery_results_taskresult.periodic_task_name
[2023-02-24 11:32:33,839: WARNING/MainProcess] Restoring 1 unacknowledged message(s)
```

**Comment by the-butterfly** [comment]
roll back to v1.8.0 works, but WHY?
