### ISSUE TITLE
Unable to install daccano on the Linux machine

### ISSUE THREAD

**Issue by as-stevens** [doccano/doccano#2188]
How to reproduce the problem
---------
Hi All,

I created a new conda environment with python 3.8.16 and python 3.9 as well.
Run the following commands
pip install doccano -- This went well

doccano init and I get the below error:
I tried pip install config, setting python path to current directory but it did not work.

Please suggest how to fix this.

```bash
Traceback (most recent call last):
  File "/etc/anaconda3/envs/nlp-annotation-tool/bin/doccano", line 8, in <module>
    sys.exit(main())
  File "/etc/anaconda3/envs/nlp-annotation-tool/lib/python3.8/site-packages/backend/cli.py", line 176, in main
    django.setup()
  File "/etc/anaconda3/envs/nlp-annotation-tool/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/etc/anaconda3/envs/nlp-annotation-tool/lib/python3.8/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/etc/anaconda3/envs/nlp-annotation-tool/lib/python3.8/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/etc/anaconda3/envs/nlp-annotation-tool/lib/python3.8/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/etc/anaconda3/envs/nlp-annotation-tool/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config.settings'
```

Your Environment
---------

*   Operating System: Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

*   Python Version Used: 3.8.16
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by wmp43** [comment]
Did you find a fix for this?
