### ISSUE TITLE
KeyError:"" during doccano init despite correct DATABASE_URL environment variable.  Trying to install Doccano with PostgreSQL

### ISSUE THREAD

**Issue by NixothePaladin** [doccano/doccano#2190]
How to reproduce the problem
1. Installed Doccano via `pip install doccano[postgreSQL]`
2. Set the environment variable DATABASE_URL `set DATABASE_URL="postgres://doccano_user:password@localhost:5432/doccano_database?sslmode=disable"` in the same terminal.  Keep in mind I put double quotation marks between the URL text.
3. Ran `doccano init`
4. Seeing error: `KeyError:''`
---------
These are my details when I set up PostgreSQL in SQL Shell (psq1). My password is just `password`

![image](https://github.com/doccano/doccano/assets/93960522/0b1dd613-8d6a-49ad-bca2-a9312daa0b50)

```bash
C:\Users\Nikko\Desktop\Uni\PX testing grounds>set DATABASE_URL="postgres://doccano_user:password@localhost:5432/doccano_database?sslmode=disable"

C:\Users\Nikko\Desktop\Uni\PX testing grounds>doccano init
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Nikko\AppData\Local\Programs\Python\Python311\Scripts\doccano.exe\__main__.py", line 7, in <module>
  File "C:\Users\Nikko\AppData\Local\Programs\Python\Python311\Lib\site-packages\backend\cli.py", line 176, in main
    django.setup()
  File "C:\Users\Nikko\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nikko\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\conf\__init__.py", line 92, in __getattr__
    self._setup(name)
  File "C:\Users\Nikko\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\conf\__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nikko\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\conf\__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nikko\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Nikko\AppData\Local\Programs\Python\Python311\Lib\site-packages\backend\config\settings\production.py", line 1, in <module>
    from .base import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nikko\AppData\Local\Programs\Python\Python311\Lib\site-packages\backend\config\settings\base.py", line 200, in <module>
    dj_database_url.config(
  File "C:\Users\Nikko\AppData\Local\Programs\Python\Python311\Lib\site-packages\dj_database_url.py", line 55, in config    config = parse(s, engine, conn_max_age, ssl_require)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nikko\AppData\Local\Programs\Python\Python311\Lib\site-packages\dj_database_url.py", line 103, in parse    engine = SCHEMES[url.scheme] if engine is None else engine
             ~~~~~~~^^^^^^^^^^^^
KeyError: ''
```

Your Environment
---------

*   Operating System: Windows 10
*   Python Version Used: Python 3.11
*   When you install doccano: 21 May 2023
*   How did you install doccano (Heroku button etc): pip install doccano[postgreSQL]

**Comment by 1XU-WANG** [comment]
我也遇到了，解决办法是不使用Postgre
