### ISSUE TITLE
InconsistentMigrationHistory exception after an upgrade to 1.8.4

### ISSUE THREAD

**Issue by kuzaxak** [doccano/doccano#2256]
How to reproduce the behaviour
---------
After an upgrade to 1.8.4 from 1.8.3 we got an exception from database init script:

```
│ doccano Traceback (most recent call last):                                                                                                                                                             │
│ doccano   File "manage.py", line 15, in <module>                                                                                                                                                       
│ doccano     execute_from_command_line(sys.argv)                                                                                                                                                        
│ doccano   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line                                                                     
│ doccano     utility.execute()                                                                                                                                                                          
│ doccano   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute                                                                                       
│ doccano     self.fetch_command(subcommand).run_from_argv(self.argv)                                                                                                                                    
│ doccano   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 402, in run_from_argv                                                                                     
│ doccano     self.execute(*args, **cmd_options)                                                                                                                                                         
│ doccano   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute                                                                                           
│ doccano     output = self.handle(*args, **options)                                                                                                                                                     
│ doccano   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 96, in wrapped                                                                                            
│ doccano     res = handle_func(*args, **kwargs)                                                                                                                                                         
│ doccano   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 117, in handle                                                                                
│ doccano     executor.loader.check_consistent_history(connection)                                                                                                                                       
│ doccano   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 327, in check_consistent_history                                                                          
│ doccano     raise InconsistentMigrationHistory(                                                                                                                                                       
│ doccano django.db.migrations.exceptions.InconsistentMigrationHistory: Migration socialaccount.0001_initial is applied before its dependency sites.0001_initial on database 'default'.
```

When downgrading to 1.8.3 doccano is able to start and operate properly.

Your Environment
---------
*   Operating System: Oficial Docker container
*   Python Version Used:
*   When you install doccano: from 1.8.0
*   How did you install doccano (Heroku button etc): Docker + Helm

**Comment by feiltom** [comment]
I test to install doccano in local in 1.8.3 with the sqlite bbd. upgrade to 1.8.4.
same problem

**Comment by WilliamsLiang** [comment]
I use doccano==1.6.2 which can deal with this problem.

**Comment by WilliamsLiang** [comment]
In Windosws, you have created a database(’C:\Users\ Your Name \doccano‘). Delete it.

**Comment by plop28** [comment]
Hello, same problem for me. After many tries, It is now solved : 

- open your DB 
- remove three records related to social account in django_migrations table (0001_initial, 0002_token_max_lengths, 0003_extra_data_default_dict)
- remove the three socialaccount tables (socialaccount_socialaccount, socialaccount_socialapp, socialaccount_socialtoken)
- upgrade your DB (I used a local doccano installation with pip so I used the doccano upgrade command)
- and for my k8s deployment, i copied back the DB to the pvc, changed the version in the deployment, and restart it
