### ISSUE TITLE
Docker not writing data to disk

### ISSUE THREAD

**Issue by CalmDownKarm** [doccano/doccano#493]
How to reproduce the behaviour
---------
Pull docker image, use docker container create as mentioned in the readme. 
Create projects as administrator -> add users through django Admin, but users can't see projects when they log in, even though they're added to the project

Further, tables in /doccano/app/db.sqlite3 in the docker image are empty - even thought the admin can see all the uploaded data/projects, no-one else can. 

Docker logs

```bash
Operations to perform:
  Apply all migrations: admin, api, auth, authtoken, contenttypes, sessions, social_django
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying api.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying sessions.0001_initial... OK
  Applying social_django.0001_initial... OK
  Applying social_django.0002_add_related_name... OK
  Applying social_django.0003_alter_email_max_length... OK
  Applying social_django.0004_auto_20160423_0400... OK
  Applying social_django.0005_auto_20160727_2333... OK
  Applying social_django.0006_partial... OK
  Applying social_django.0007_code_timestamp... OK
  Applying social_django.0008_partial_timestamp... OK
Role created successfully "project_admin"
Role created successfully "annotator"
Role created successfully "annotation_approver"
Superuser created successfully.
[2019-12-09 10:37:38 +0000] [146] [INFO] Starting gunicorn 19.9.0
[2019-12-09 10:37:38 +0000] [146] [INFO] Listening at: http://0.0.0.0:8000 (146)
[2019-12-09 10:37:38 +0000] [146] [INFO] Using worker: sync
[2019-12-09 10:37:38 +0000] [149] [INFO] Booting worker with pid: 149
[2019-12-09 10:37:38 +0000] [150] [INFO] Booting worker with pid: 150
Not Found: /favicon.ico
Not Found: /projects/admin
Not Found: /favicon.ico
Internal Server Error: /projects/1/docs/create
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 149, in get
    context = self.get_context_data(**kwargs)
  File "/doccano/app/server/views.py", line 87, in get_context_data
    context['bundle_name'] = project.get_bundle_name_upload()
  File "/doccano/app/api/models.py", line 47, in get_bundle_name_upload
    raise NotImplementedError()
NotImplementedError
Internal Server Error: /projects/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 149, in get
    context = self.get_context_data(**kwargs)
  File "/doccano/app/server/views.py", line 33, in get_context_data
    context['bundle_name'] = project.get_bundle_name()
  File "/doccano/app/api/models.py", line 44, in get_bundle_name
    raise NotImplementedError()
NotImplementedError
Bad Request: /v1/projects/2/docs/upload
Bad Request: /v1/projects/2/docs/upload
Bad Request: /v1/projects/2/docs/upload
Bad Request: /v1/projects/2/labels/3
/usr/local/lib/python3.6/site-packages/django/views/generic/list.py:88: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.Document'> QuerySet.
  allow_empty_first_page=allow_empty_first_page, **kwargs)
Bad Request: /v1/projects/3/docs/upload
Bad Request: /v1/projects/3/docs/upload
Bad Request: /v1/projects
/usr/local/lib/python3.6/site-packages/django/views/generic/list.py:88: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.Document'> QuerySet.
  allow_empty_first_page=allow_empty_first_page, **kwargs)
Not Found: /v1/projects
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /v1/projects
Not Found: /v1/projects
Not Found: /v1/projects
Not Found: /v1/projects
Not Found: /v1/projects
Not Found: /v1/projects
Not Found: /v1/projects
Internal Server Error: /projects/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 149, in get
    context = self.get_context_data(**kwargs)
  File "/doccano/app/server/views.py", line 33, in get_context_data
    context['bundle_name'] = project.get_bundle_name()
  File "/doccano/app/api/models.py", line 44, in get_bundle_name
    raise NotImplementedError()
NotImplementedError
Not Found: /favicon.ico
Not Found: /projects/v1
Operations to perform:
  Apply all migrations: admin, api, auth, authtoken, contenttypes, sessions, social_django
Running migrations:
  No migrations to apply.
Datbase Error: "UNIQUE constraint failed: api_role.name"
Datbase Error: "UNIQUE constraint failed: api_role.name"
Datbase Error: "UNIQUE constraint failed: api_role.name"
User admin already exists.
[2019-12-10 10:21:12 +0000] [146] [INFO] Starting gunicorn 19.9.0
[2019-12-10 10:21:12 +0000] [146] [INFO] Listening at: http://0.0.0.0:8000 (146)
[2019-12-10 10:21:12 +0000] [146] [INFO] Using worker: sync
[2019-12-10 10:21:12 +0000] [149] [INFO] Booting worker with pid: 149
[2019-12-10 10:21:12 +0000] [151] [INFO] Booting worker with pid: 151
Not Found: /v1/projects
Not Found: /projects/admin
/usr/local/lib/python3.6/site-packages/django/views/generic/list.py:88: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.Document'> QuerySet.
  allow_empty_first_page=allow_empty_first_page, **kwargs)
Not Found: /v1/projects
/usr/local/lib/python3.6/site-packages/django/views/generic/list.py:88: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'api.models.Document'> QuerySet.
  allow_empty_first_page=allow_empty_first_page, **kwargs)
Not Found: /favicon.ico
Not Found: /v1/projects
Not Found: /v1/projects
Not Found: /favicon.ico
Not Found: /v1/projects
Not Found: /favicon.ico
Not Found: /v1/projects
```

**Comment by fsuste** [comment]
@CalmDownKarm Did you fix this? And how?

**Comment by CalmDownKarm** [comment]
@fsuste Nope, couldn't figure it out so didn't use doccano - built my own.

**Comment by at-a-run** [comment]
This still seems to be an issue. As you can see below, none of the files have changed since April 10 and I have annotated several times since then. @icoxfog417 @Hironsan can we please reopen this or should I create a new issue?
```
$ docker exec -i doccano /bin/bash - << EOF
ls -latrh "app"
EOF
total 436K
drwxr-xr-x  2 doccano doccano 4.0K Apr 10 06:14 tools
-rw-r--r--  1 doccano doccano  950 Apr 10 06:14 requirements.txt
-rwxr-xr-x  1 doccano doccano  535 Apr 10 06:14 manage.py
drwxr-xr-x  2 doccano doccano 4.0K Apr 10 06:14 classifier
-rw-r--r--  1 doccano doccano    0 Apr 10 06:14 __init__.py
-rw-r--r--  1 doccano doccano  463 Apr 10 06:14 Dockerfile
-rw-r--r--  1 doccano doccano  126 Apr 10 06:14 .dockerignore
drwxr-xr-x  1 doccano doccano 4.0K Apr 10 06:29 app
drwxr-xr-x  1 doccano doccano 4.0K Apr 10 06:29 server
drwxr-xr-x  5 doccano doccano 4.0K Apr 10 06:29 api
drwxr-xr-x  6 doccano doccano 4.0K Apr 10 06:29 authentification
-rw-r--r--  1 doccano doccano 364K Apr 10 06:29 db.sqlite3
drwxr-xr-x  1 doccano doccano 4.0K Apr 10 06:32 .
drwxr-xr-x  2 doccano doccano 4.0K Apr 10 06:32 junitxml
drwxr-xr-x 11 doccano doccano 4.0K Apr 10 06:37 staticfiles
drwxr-xr-x  1 root    root    4.0K Apr 10 06:39 ..

$ docker image ls
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
doccano/doccano     latest              4f018c685336        4 weeks ago         459MB

**Comment by icoxfog417** [comment]
We can't reproduce this error. @at-a-run if you can reproduce this, please raise a new issue.

**Comment by Josleee** [comment]
I encountered the same issue. I deployed doccano using one-click AWS deployment.

`$ sudo docker exec -i doccano /bin/bash - << EOF
ls -latrh "app"
EOF
total 420K
drwxrwxr-x  2 doccano doccano 4.0K Apr 20 05:18 tools
-rw-rw-r--  1 doccano doccano  950 Apr 20 05:18 requirements.txt
-rwxrwxr-x  1 doccano doccano  535 Apr 20 05:18 manage.py
drwxrwxr-x  2 doccano doccano 4.0K Apr 20 05:18 classifier
-rw-rw-r--  1 doccano doccano    0 Apr 20 05:18 __init__.py
-rw-rw-r--  1 doccano doccano  463 Apr 20 05:18 Dockerfile
-rw-rw-r--  1 doccano doccano  126 Apr 20 05:18 .dockerignore
drwxrwxr-x  1 doccano doccano 4.0K Apr 20 05:23 server
drwxrwxr-x  6 doccano doccano 4.0K Apr 20 05:23 authentification
drwxrwxr-x  1 doccano doccano 4.0K Apr 20 05:23 app
drwxrwxr-x  5 doccano doccano 4.0K Apr 20 05:23 api
-rw-r--r--  1 doccano doccano 364K Apr 20 05:23 db.sqlite3
drwxr-xr-x  2 doccano doccano 4.0K Apr 20 05:23 junitxml
drwxrwxr-x  1 doccano doccano 4.0K Apr 20 05:23 .
drwxr-xr-x 11 doccano doccano 4.0K Apr 20 05:25 staticfiles
drwxr-xr-x  1 root    root    4.0K Apr 20 05:26 ..`
