### ISSUE TITLE
npm run build failed with #247

### ISSUE THREAD

**Issue by fatih-erarslan** [doccano/doccano#641]
Hi @Hironsan 

First, I am sorry about formatting this message, I will appreciate if you please can take a look at the issue.

I am having the same issue per #247 although I have the latest Node.js v13.11.0 & npm v6.13.7.
reinstalled the package and followed your instructions.

My environment is macOS catalina 15.3, Python3.8.2, venv, with Django 2.2.10, I am not using Docker, trying to get it working without.

serving on port 3000  with `dev-nuxt-run.sh` works fine. 

When I run `npm run build` at `app/server/static` I get this error:

```
`> Executing task in folder doccano: npm run build <`

source /Users/fatih/Desktop/Projects/AI/doccano/venv/bin/activate

> server@1.0.0 build /Users/fatih/Desktop/Projects/AI/doccano/app/server/static
> webpack

Hash: 56cf4396341b0113ac29
Version: webpack 4.42.0
Time: 7435ms
Built at: 03/23/2020 11:18:12 AM

...
upload_text_classification
                       users.js  2.32 MiB                         users  ``[emitted]  users
Entrypoint dataset = dataset.js`
...
Entrypoint download_text_classification = download_text_classification.js
...
[./pages/sequence_labeling.js] 273 bytes {sequence_labeling} [built]
[./pages/stats.js] 154 bytes {stats} [built]
    + 242 hidden modules

ERROR in ./components/stats.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./components/stats.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'vue-chartjs/es/BaseCharts/Doughnut' in '/Users/fatih/Desktop/Projects/AI/doccano/app/server/static/components'
 @ ./components/stats.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./components/stats.vue?vue&type=script&lang=js&) 36:0-58 76:11-19
 @ ./components/stats.vue?vue&type=script&lang=js&
 @ ./components/stats.vue
 @ ./pages/stats.js

ERROR in ./components/stats.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./components/stats.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'vue-chartjs/es/BaseCharts/HorizontalBar' in '/Users/fatih/Desktop/Projects/AI/doccano/app/server/static/components'
 @ ./components/stats.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./components/stats.vue?vue&type=script&lang=js&) 35:0-68 41:11-24
 @ ./components/stats.vue?vue&type=script&lang=js&
 @ ./components/stats.vue
 @ ./pages/stats.js

ERROR in ./components/stats.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./components/stats.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'vue-chartjs/es/mixins/reactiveProp' in '/Users/fatih/Desktop/Projects/AI/doccano/app/server/static/components'
 @ ./components/stats.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./components/stats.vue?vue&type=script&lang=js&) 37:0-62 43:11-23 78:11-23
 @ ./components/stats.vue?vue&type=script&lang=js&
 @ ./components/stats.vue
 @ ./pages/stats.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! server@1.0.0 build:` `webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the server@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fatih/.npm/_logs/2020-03-23T08_18_12_798Z-debug.log
The terminal process terminated with exit code: 2
```

Django starts OK with:
```
source /Users/fatih/Desktop/Projects/AI/doccano/venv/bin/activate
echo "Starting Django Backend Server"

gunicorn --bind="0.0.0.0:${PORT:-8000}" --workers="${WORKERS:-1}" --pythonpath=app app.wsgi --timeout 300 
```

but then when I access to it assuming that i have a messed up nginx.conf to blame, it goes like this:

```
> Executing task in folder doccano: npm run Django <

source /Users/fatih/Desktop/Projects/AI/doccano/venv/bin/activate

> @ Django /Users/fatih/Desktop/Projects/AI/doccano
> sh tools/django.sh
```

```
Starting Django Backend Server
[2020-03-23 10:49:50 +0300] [29032] [INFO] Starting gunicorn 20.0.4
[2020-03-23 10:49:50 +0300] [29032] [INFO] Listening at: http://0.0.0.0:8000 (29032)
[2020-03-23 10:49:50 +0300] [29032] [INFO] Using worker: sync
[2020-03-23 10:49:50 +0300] [29049] [INFO] Booting worker with pid: 29049
Internal Server Error: /projects/
Traceback (most recent call last):
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle
    tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/webpack_loader/utils.py", line 62, in get_as_tags
    bundle = _get_bundle(bundle_name, extension, config)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/webpack_loader/utils.py", line 40, in _get_bundle
    bundle = get_loader(config).get_bundle(bundle_name)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/webpack_loader/loader.py", line 96, in get_bundle
    raise WebpackError(error)
webpack_loader.exceptions.WebpackError: 
            ModuleNotFoundError in 
            Module not found: Error: Can't resolve 'vue-chartjs/es/BaseCharts/Doughnut' in '/Users/fatih/Desktop/Projects/AI/doccano/app/server/static/components'
```

```            
Not Found: /favicon.ico
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle
    tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/webpack_loader/utils.py", line 62, in get_as_tags
    bundle = _get_bundle(bundle_name, extension, config)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/webpack_loader/utils.py", line 40, in _get_bundle
    bundle = get_loader(config).get_bundle(bundle_name)
  File "/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/webpack_loader/loader.py", line 96, in get_bundle
    raise WebpackError(error)
webpack_loader.exceptions.WebpackError: 
            ModuleNotFoundError in 
            Module not found: Error: Can't resolve 'vue-chartjs/es/BaseCharts/Doughnut' in '/Users/fatih/Desktop/Projects/AI/doccano/app/server/static/components'
```

### and I have internal server error at port 80 (nginx) also this at port 8000:

```
Request Method: | GET
-- | --
http://0.0.0.0:8000/
2.2.10
WebpackError
ModuleNotFoundError in              Module not found: Error: Can't resolve 'vue-chartjs/es/BaseCharts/Doughnut' in '/Users/fatih/Desktop/Projects/AI/doccano/app/server/static/components'
/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages/webpack_loader/loader.py in get_bundle, line 96
/Users/fatih/Desktop/Projects/AI/doccano/venv/bin/python3
3.8.2
['/Users/fatih/Desktop/Projects/AI/doccano/app',  '/Users/fatih/Desktop/Projects/AI/doccano',  '/Users/fatih/Desktop/Projects/AI/doccano/venv/bin',  '/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip',  '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8',  '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload',  '/Users/fatih/Desktop/Projects/AI/doccano/venv/lib/python3.8/site-packages',  '/Users/fatih/Library/Python/3.8/lib/python/site-packages',  '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages',  '../api']
Mon, 23 Mar 2020 08:12:25 +0000
```

Your Environment
---------

*   Operating System: macOS Catalina 15.3
*   Python Version Used: 3.8.2
*   When you install doccano: app/server/static does not compile 
*   How did you install doccano (Heroku button etc): directly on the system

```
Django |   | 2.2.10
Python |   | 3.8.2
debug_toolbar | Debug Toolbar | 2.2
django_filters | Django_Filters | 2.2.0
polymorphic | Polymorphic | 2.1.2
rest_framework | Django REST framework | 3.11.0
social_django | Python Social Auth | 3.1.0
webpack_loader | Webpack Loader | 0.7.0
```

### webpack-stats.json:

```
{"status":"error","error":"ModuleNotFoundError","message":"Module not found: Error: Can't resolve 'vue-chartjs/es/BaseCharts/Doughnut' in '/Users/fatih/Desktop/Projects/AI/doccano/app/server/static/components'"}
```

npm log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'lint' ]
2 info using npm@6.13.7
3 info using node@v13.11.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle server@1.0.0~prelint: server@1.0.0
6 info lifecycle server@1.0.0~lint: server@1.0.0
7 verbose lifecycle server@1.0.0~lint: unsafe-perm in lifecycle true
8 verbose lifecycle server@1.0.0~lint: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/fatih/Desktop/Projects/AI/doccano/app/server/static/node_modules/.bin:/Users/fatih/google-cloud-sdk/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/Users/fatih/opt/anaconda3/bin:/Applications/Xcode.app/Contents/Developer:/usr/local/mongodb/bin:/usr/local/opt/python/3.8.2/bin:/usr/local/opt/qt/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Postgres.app/Contents/Versions/latest/bin
9 verbose lifecycle server@1.0.0~lint: CWD: /Users/fatih/Desktop/Projects/AI/doccano/app/server/static
10 silly lifecycle server@1.0.0~lint: Args: [ '-c', 'run-s lint.js lint.pug lint.pug.vue' ]
11 silly lifecycle server@1.0.0~lint: Returned: code: 1  signal: null
12 info lifecycle server@1.0.0~lint: Failed to exec lint script
13 verbose stack Error: server@1.0.0 lint: `run-s lint.js lint.pug lint.pug.vue`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid server@1.0.0
15 verbose cwd /Users/fatih/Desktop/Projects/AI/doccano/app/server/static
16 verbose Darwin 19.3.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint"
18 verbose node v13.11.0
19 verbose npm  v6.13.7
20 error code ELIFECYCLE
21 error errno 1
22 error server@1.0.0 lint: `run-s lint.js lint.pug lint.pug.vue`
22 error Exit status 1
23 error Failed at the server@1.0.0 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Hironsan** [comment]
Hi @fatih-erarslan,  
If you run doccano from source, please run the following command:

```
# clone repository
git clone https://github.com/doccano/doccano.git

# Python settings
cd doccano/app
pip install -r requirements.txt
python manage.py migrate
python manage.py create_roles
python manage.py createsuperuser
python manage.py runserver

# Node settings
cd ../frontend
npm install
npm run dev
```

**Comment by brightgems** [comment]
Looks like app folder is a django project, which use webpack transparently with Django + hot reloading Vue components.

In order to browse localhost:8000/admin site, I need to run `npm run build` and then webpack-stats.json file can generated.

I encounter the same issue as above, but solve it with minor change to source code

*before*
```
import HorizontalBar from 'vue-chartjs/es/BaseCharts/HorizontalBar';
import Doughnut from 'vue-chartjs/es/BaseCharts/Doughnut';
import reactiveProp from 'vue-chartjs/es/mixins/reactiveProp';
```

after
```
import { HorizontalBar, Doughnut, reactiveProp } from 'vue-chartjs';
```
