### ISSUE TITLE
Error Starting doccano_frontend container when trying to set up (development) environment with docker-compose

### ISSUE THREAD

**Issue by David192** [doccano/doccano#846]
### System information
- **Ubuntu 18.04.2 LTS**:

### Describe the problem
The frontend docker container fails to start when trying to set up doccano for local development environment. 
It seems related to older issues of this kind ("Cannot find module 'eslint-plugin-nuxt'"), but applying those fixes didn't work for me, or I might miss something obvious here.

Thank for your help. 

Using `docker-compose -f docker-compose.dev.yml up`:

### Source code / logs
```
Creating doccano_postgres_1 ... done
Creating doccano_backend_1  ... done
Creating doccano_frontend_1 ... done
Attaching to doccano_postgres_1, doccano_backend_1, doccano_frontend_1
postgres_1  | 2020-06-16 11:52:44.309 UTC [1] LOG:  starting PostgreSQL 12.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
postgres_1  | 2020-06-16 11:52:44.309 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2020-06-16 11:52:44.309 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2020-06-16 11:52:44.314 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2020-06-16 11:52:44.339 UTC [18] LOG:  database system was interrupted; last known up at 2020-06-16 11:43:41 UTC
postgres_1  | 2020-06-16 11:52:44.373 UTC [18] LOG:  database system was not properly shut down; automatic recovery in progress
postgres_1  | 2020-06-16 11:52:44.377 UTC [18] LOG:  redo starts at 0/17862F0
postgres_1  | 2020-06-16 11:52:44.377 UTC [18] LOG:  invalid record length at 0/17863D8: wanted 24, got 0
postgres_1  | 2020-06-16 11:52:44.377 UTC [18] LOG:  redo done at 0/17863A0
postgres_1  | 2020-06-16 11:52:44.401 UTC [1] LOG:  database system is ready to accept connections
backend_1   | Installing dependencies
backend_1   | Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
backend_1   | Get:2 http://deb.debian.org/debian buster InRelease [121 kB]
backend_1   | Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
backend_1   | Get:4 http://deb.debian.org/debian buster/main amd64 Packages [7905 kB]
backend_1   | Get:5 http://deb.debian.org/debian buster-updates/main amd64 Packages [7868 B]
frontend_1  | Starting frontend server
backend_1   | Get:6 http://security.debian.org/debian-security buster/updates/main amd64 Packages [203 kB]
frontend_1  | 
frontend_1  | > doccano@1.0.0 lintfix /src/frontend
frontend_1  | > eslint --fix --ext .js,.vue --ignore-path .gitignore .
frontend_1  | 
backend_1   | Fetched 8355 kB in 2s (4611 kB/s)
frontend_1  | Cannot find module 'eslint-plugin-nuxt'
frontend_1  | Require stack:
frontend_1  | - /src/frontend/node_modules/eslint/lib/config/config-file.js
frontend_1  | - /src/frontend/node_modules/eslint/lib/config.js
frontend_1  | - /src/frontend/node_modules/eslint/lib/cli-engine.js
frontend_1  | - /src/frontend/node_modules/eslint/lib/cli.js
frontend_1  | - /src/frontend/node_modules/eslint/bin/eslint.js
frontend_1  | Referenced from: /src/frontend/.eslintrc.js
frontend_1  | Error: Cannot find module 'eslint-plugin-nuxt'
frontend_1  | Require stack:
frontend_1  | - /src/frontend/node_modules/eslint/lib/config/config-file.js
frontend_1  | - /src/frontend/node_modules/eslint/lib/config.js
frontend_1  | - /src/frontend/node_modules/eslint/lib/cli-engine.js
frontend_1  | - /src/frontend/node_modules/eslint/lib/cli.js
frontend_1  | - /src/frontend/node_modules/eslint/bin/eslint.js
frontend_1  | Referenced from: /src/frontend/.eslintrc.js
frontend_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:954:17)
frontend_1  |     at Function.resolve (internal/modules/cjs/helpers.js:75:19)
frontend_1  |     at resolve (/src/frontend/node_modules/eslint/lib/config/config-file.js:475:31)
frontend_1  |     at load (/src/frontend/node_modules/eslint/lib/config/config-file.js:556:26)
frontend_1  |     at /src/frontend/node_modules/eslint/lib/config/config-file.js:430:36
frontend_1  |     at Array.reduceRight (<anonymous>)
frontend_1  |     at applyExtends (/src/frontend/node_modules/eslint/lib/config/config-file.js:408:26)
frontend_1  |     at loadFromDisk (/src/frontend/node_modules/eslint/lib/config/config-file.js:528:22)
frontend_1  |     at Object.load (/src/frontend/node_modules/eslint/lib/config/config-file.js:564:20)
frontend_1  |     at Config.getLocalConfigHierarchy (/src/frontend/node_modules/eslint/lib/config.js:227:44)
frontend_1  | npm ERR! code ELIFECYCLE
frontend_1  | npm ERR! errno 2
frontend_1  | npm ERR! doccano@1.0.0 lintfix: `eslint --fix --ext .js,.vue --ignore-path .gitignore .`
frontend_1  | npm ERR! Exit status 2
frontend_1  | npm ERR! 
frontend_1  | npm ERR! Failed at the doccano@1.0.0 lintfix script.
frontend_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
frontend_1  | 
frontend_1  | npm ERR! A complete log of this run can be found in:
frontend_1  | npm ERR!     /root/.npm/_logs/2020-06-16T11_52_47_593Z-debug.log
backend_1   | Reading package lists...
doccano_frontend_1 exited with code 2
backend_1   | Reading package lists...
backend_1   | Building dependency tree...
backend_1   | Reading state information...
backend_1   | g++ is already the newest version (4:8.3.0-1).
backend_1   | The following additional packages will be installed:
backend_1   |   libodbc1 odbcinst odbcinst1debian2
backend_1   | Suggested packages:
backend_1   |   libmyodbc odbc-postgresql tdsodbc unixodbc-bin
backend_1   | The following NEW packages will be installed:
backend_1   |   libodbc1 odbcinst odbcinst1debian2 unixodbc-dev
backend_1   | 0 upgraded, 4 newly installed, 0 to remove and 59 not upgraded.
backend_1   | Need to get 610 kB of archives.
backend_1   | After this operation, 2784 kB of additional disk space will be used.
backend_1   | Get:1 http://deb.debian.org/debian buster/main amd64 libodbc1 amd64 2.3.6-0.1 [223 kB]
backend_1   | Get:2 http://deb.debian.org/debian buster/main amd64 odbcinst1debian2 amd64 2.3.6-0.1 [78.1 kB]
backend_1   | Get:3 http://deb.debian.org/debian buster/main amd64 odbcinst amd64 2.3.6-0.1 [48.4 kB]
backend_1   | Get:4 http://deb.debian.org/debian buster/main amd64 unixodbc-dev amd64 2.3.6-0.1 [261 kB]
backend_1   | debconf: delaying package configuration, since apt-utils is not installed
backend_1   | Fetched 610 kB in 0s (35.8 MB/s)
backend_1   | Selecting previously unselected package libodbc1:amd64.
(Reading database ... 24593 files and directories currently installed.)
backend_1   | Preparing to unpack .../libodbc1_2.3.6-0.1_amd64.deb ...
backend_1   | Unpacking libodbc1:amd64 (2.3.6-0.1) ...
backend_1   | Selecting previously unselected package odbcinst1debian2:amd64.
backend_1   | Preparing to unpack .../odbcinst1debian2_2.3.6-0.1_amd64.deb ...
backend_1   | Unpacking odbcinst1debian2:amd64 (2.3.6-0.1) ...
backend_1   | Selecting previously unselected package odbcinst.
backend_1   | Preparing to unpack .../odbcinst_2.3.6-0.1_amd64.deb ...
backend_1   | Unpacking odbcinst (2.3.6-0.1) ...
backend_1   | Selecting previously unselected package unixodbc-dev:amd64.
backend_1   | Preparing to unpack .../unixodbc-dev_2.3.6-0.1_amd64.deb ...
backend_1   | Unpacking unixodbc-dev:amd64 (2.3.6-0.1) ...
backend_1   | Setting up libodbc1:amd64 (2.3.6-0.1) ...
backend_1   | Setting up odbcinst (2.3.6-0.1) ...
backend_1   | Setting up odbcinst1debian2:amd64 (2.3.6-0.1) ...
backend_1   | Setting up unixodbc-dev:amd64 (2.3.6-0.1) ...
backend_1   | Processing triggers for libc-bin (2.28-10) ...
backend_1   | Requirement already satisfied: apache-libcloud==2.4.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 1)) (2.4.0)
backend_1   | Requirement already satisfied: applicationinsights==0.11.7 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 2)) (0.11.7)
backend_1   | Requirement already satisfied: colour==0.1.5 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 3)) (0.1.5)
backend_1   | Requirement already satisfied: chardet==3.0.4 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 4)) (3.0.4)
backend_1   | Requirement already satisfied: coverage==4.5.3 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 5)) (4.5.3)
backend_1   | Requirement already satisfied: dj-database-url==0.5.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 6)) (0.5.0)
backend_1   | Collecting Django==2.2.10
backend_1   |   Downloading Django-2.2.10-py3-none-any.whl (7.5 MB)
backend_1   | Requirement already satisfied: django-cloud-browser==0.5.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 8)) (0.5.0)
backend_1   | Requirement already satisfied: django-cors-headers==3.1.1 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 9)) (3.1.1)
backend_1   | Requirement already satisfied: django-filter==2.0.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 10)) (2.0.0)
backend_1   | Requirement already satisfied: django-heroku==0.3.1 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 11)) (0.3.1)
backend_1   | Requirement already satisfied: django-webpack-loader==0.6.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 12)) (0.6.0)
backend_1   | Requirement already satisfied: django-widget-tweaks==1.4.2 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 13)) (1.4.2)
backend_1   | Requirement already satisfied: django-polymorphic==2.0.3 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 14)) (2.0.3)
backend_1   | Requirement already satisfied: django-pyodbc-azure==2.1.0.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 15)) (2.1.0.0)
backend_1   | Requirement already satisfied: django-rest-polymorphic==0.1.8 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 16)) (0.1.8)
backend_1   | Requirement already satisfied: djangorestframework==3.10 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 17)) (3.10.0)
backend_1   | Requirement already satisfied: djangorestframework-csv==2.1.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 18)) (2.1.0)
backend_1   | Requirement already satisfied: djangorestframework-filters==0.10.2 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 19)) (0.10.2)
backend_1   | Requirement already satisfied: drf-yasg==1.17.1 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 20)) (1.17.1)
backend_1   | Requirement already satisfied: environs==4.1.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 21)) (4.1.0)
backend_1   | Requirement already satisfied: djangorestframework-xml==1.4.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 22)) (1.4.0)
backend_1   | Requirement already satisfied: Faker==0.9.1 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 23)) (0.9.1)
backend_1   | Requirement already satisfied: flake8==3.6.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 24)) (3.6.0)
backend_1   | Requirement already satisfied: furl==2.0.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 25)) (2.0.0)
backend_1   | Requirement already satisfied: gunicorn==19.9.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 26)) (19.9.0)
backend_1   | Requirement already satisfied: lockfile==0.12.2 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 27)) (0.12.2)
backend_1   | Requirement already satisfied: model-mommy==1.6.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 28)) (1.6.0)
backend_1   | Requirement already satisfied: psycopg2-binary==2.7.7 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 29)) (2.7.7)
backend_1   | Requirement already satisfied: pyexcel==0.5.14 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 30)) (0.5.14)
backend_1   | Requirement already satisfied: pyexcel-xlsx==0.5.7 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 31)) (0.5.7)
backend_1   | Requirement already satisfied: python-dateutil==2.7.3 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 32)) (2.7.3)
backend_1   | Requirement already satisfied: pytz==2018.4 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 33)) (2018.4)
backend_1   | Requirement already satisfied: requests==2.21.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 34)) (2.21.0)
backend_1   | Requirement already satisfied: six==1.11.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 35)) (1.11.0)
backend_1   | Requirement already satisfied: seqeval==0.0.6 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 36)) (0.0.6)
backend_1   | Requirement already satisfied: social-auth-app-django==3.1.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 37)) (3.1.0)
backend_1   | Requirement already satisfied: social-auth-core[azuread]==3.0.0 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 38)) (3.0.0)
backend_1   | Requirement already satisfied: text-unidecode==1.2 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 39)) (1.2)
backend_1   | Requirement already satisfied: unittest-xml-reporting==2.5.1 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 40)) (2.5.1)
backend_1   | Requirement already satisfied: vcrpy==2.0.1 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 41)) (2.0.1)
backend_1   | Requirement already satisfied: vcrpy-unittest==0.1.7 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 42)) (0.1.7)
backend_1   | Requirement already satisfied: whitenoise[brotli]==4.1.2 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 43)) (4.1.2)
backend_1   | Requirement already satisfied: conllu==1.3.2 in /src/venv/lib/python3.6/site-packages (from -r /src/app/tools/../../app/requirements.txt (line 44)) (1.3.2)
backend_1   | Requirement already satisfied: sqlparse in /src/venv/lib/python3.6/site-packages (from Django==2.2.10->-r /src/app/tools/../../app/requirements.txt (line 7)) (0.3.1)
backend_1   | Requirement already satisfied: psycopg2 in /src/venv/lib/python3.6/site-packages (from django-heroku==0.3.1->-r /src/app/tools/../../app/requirements.txt (line 11)) (2.8.4)
backend_1   | Requirement already satisfied: pyodbc>=3.0 in /src/venv/lib/python3.6/site-packages (from django-pyodbc-azure==2.1.0.0->-r /src/app/tools/../../app/requirements.txt (line 15)) (4.0.28)
backend_1   | Requirement already satisfied: unicodecsv in /src/venv/lib/python3.6/site-packages (from djangorestframework-csv==2.1.0->-r /src/app/tools/../../app/requirements.txt (line 18)) (0.14.1)
backend_1   | Requirement already satisfied: coreschema>=0.0.4 in /src/venv/lib/python3.6/site-packages (from drf-yasg==1.17.1->-r /src/app/tools/../../app/requirements.txt (line 20)) (0.0.4)
backend_1   | Requirement already satisfied: uritemplate>=3.0.0 in /src/venv/lib/python3.6/site-packages (from drf-yasg==1.17.1->-r /src/app/tools/../../app/requirements.txt (line 20)) (3.0.1)
backend_1   | Requirement already satisfied: packaging in /src/venv/lib/python3.6/site-packages (from drf-yasg==1.17.1->-r /src/app/tools/../../app/requirements.txt (line 20)) (20.4)
backend_1   | Requirement already satisfied: coreapi>=2.3.3 in /src/venv/lib/python3.6/site-packages (from drf-yasg==1.17.1->-r /src/app/tools/../../app/requirements.txt (line 20)) (2.3.3)
backend_1   | Requirement already satisfied: ruamel.yaml>=0.15.34 in /src/venv/lib/python3.6/site-packages (from drf-yasg==1.17.1->-r /src/app/tools/../../app/requirements.txt (line 20)) (0.16.10)
backend_1   | Requirement already satisfied: inflection>=0.3.1 in /src/venv/lib/python3.6/site-packages (from drf-yasg==1.17.1->-r /src/app/tools/../../app/requirements.txt (line 20)) (0.5.0)
backend_1   | Requirement already satisfied: python-dotenv in /src/venv/lib/python3.6/site-packages (from environs==4.1.0->-r /src/app/tools/../../app/requirements.txt (line 21)) (0.10.5)
backend_1   | Requirement already satisfied: marshmallow>=2.7.0 in /src/venv/lib/python3.6/site-packages (from environs==4.1.0->-r /src/app/tools/../../app/requirements.txt (line 21)) (3.3.0)
backend_1   | Requirement already satisfied: defusedxml>=0.3 in /src/venv/lib/python3.6/site-packages (from djangorestframework-xml==1.4.0->-r /src/app/tools/../../app/requirements.txt (line 22)) (0.6.0)
backend_1   | Requirement already satisfied: setuptools>=30 in /src/venv/lib/python3.6/site-packages (from flake8==3.6.0->-r /src/app/tools/../../app/requirements.txt (line 24)) (45.1.0)
backend_1   | Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /src/venv/lib/python3.6/site-packages (from flake8==3.6.0->-r /src/app/tools/../../app/requirements.txt (line 24)) (0.6.1)
backend_1   | Requirement already satisfied: pycodestyle<2.5.0,>=2.4.0 in /src/venv/lib/python3.6/site-packages (from flake8==3.6.0->-r /src/app/tools/../../app/requirements.txt (line 24)) (2.4.0)
backend_1   | Requirement already satisfied: pyflakes<2.1.0,>=2.0.0 in /src/venv/lib/python3.6/site-packages (from flake8==3.6.0->-r /src/app/tools/../../app/requirements.txt (line 24)) (2.0.0)
backend_1   | Requirement already satisfied: orderedmultidict>=1.0 in /src/venv/lib/python3.6/site-packages (from furl==2.0.0->-r /src/app/tools/../../app/requirements.txt (line 25)) (1.0.1)
backend_1   | Requirement already satisfied: lml>=0.0.4 in /src/venv/lib/python3.6/site-packages (from pyexcel==0.5.14->-r /src/app/tools/../../app/requirements.txt (line 30)) (0.0.9)
backend_1   | Requirement already satisfied: pyexcel-io>=0.5.18 in /src/venv/lib/python3.6/site-packages (from pyexcel==0.5.14->-r /src/app/tools/../../app/requirements.txt (line 30)) (0.5.20)
backend_1   | Requirement already satisfied: texttable>=0.8.2 in /src/venv/lib/python3.6/site-packages (from pyexcel==0.5.14->-r /src/app/tools/../../app/requirements.txt (line 30)) (1.6.2)
backend_1   | Requirement already satisfied: openpyxl<2.6.0,>=2.5.0 in /src/venv/lib/python3.6/site-packages (from pyexcel-xlsx==0.5.7->-r /src/app/tools/../../app/requirements.txt (line 31)) (2.5.14)
backend_1   | Requirement already satisfied: certifi>=2017.4.17 in /src/venv/lib/python3.6/site-packages (from requests==2.21.0->-r /src/app/tools/../../app/requirements.txt (line 34)) (2019.11.28)
backend_1   | Requirement already satisfied: urllib3<1.25,>=1.21.1 in /src/venv/lib/python3.6/site-packages (from requests==2.21.0->-r /src/app/tools/../../app/requirements.txt (line 34)) (1.24.3)
backend_1   | Requirement already satisfied: idna<2.9,>=2.5 in /src/venv/lib/python3.6/site-packages (from requests==2.21.0->-r /src/app/tools/../../app/requirements.txt (line 34)) (2.8)
backend_1   | Requirement already satisfied: numpy>=1.14.0 in /src/venv/lib/python3.6/site-packages (from seqeval==0.0.6->-r /src/app/tools/../../app/requirements.txt (line 36)) (1.18.1)
backend_1   | Requirement already satisfied: oauthlib>=1.0.3 in /src/venv/lib/python3.6/site-packages (from social-auth-core[azuread]==3.0.0->-r /src/app/tools/../../app/requirements.txt (line 38)) (3.1.0)
backend_1   | Requirement already satisfied: requests-oauthlib>=0.6.1 in /src/venv/lib/python3.6/site-packages (from social-auth-core[azuread]==3.0.0->-r /src/app/tools/../../app/requirements.txt (line 38)) (1.3.0)
backend_1   | Requirement already satisfied: python3-openid>=3.0.10; python_version >= "3.0" in /src/venv/lib/python3.6/site-packages (from social-auth-core[azuread]==3.0.0->-r /src/app/tools/../../app/requirements.txt (line 38)) (3.1.0)
backend_1   | Requirement already satisfied: PyJWT>=1.4.0 in /src/venv/lib/python3.6/site-packages (from social-auth-core[azuread]==3.0.0->-r /src/app/tools/../../app/requirements.txt (line 38)) (1.7.1)
backend_1   | Requirement already satisfied: cryptography>=2.1.1; extra == "azuread" in /src/venv/lib/python3.6/site-packages (from social-auth-core[azuread]==3.0.0->-r /src/app/tools/../../app/requirements.txt (line 38)) (2.8)
backend_1   | Requirement already satisfied: yarl; python_version >= "3.4" in /src/venv/lib/python3.6/site-packages (from vcrpy==2.0.1->-r /src/app/tools/../../app/requirements.txt (line 41)) (1.4.2)
backend_1   | Requirement already satisfied: wrapt in /src/venv/lib/python3.6/site-packages (from vcrpy==2.0.1->-r /src/app/tools/../../app/requirements.txt (line 41)) (1.11.2)
backend_1   | Requirement already satisfied: PyYAML in /src/venv/lib/python3.6/site-packages (from vcrpy==2.0.1->-r /src/app/tools/../../app/requirements.txt (line 41)) (5.3)
backend_1   | Requirement already satisfied: Brotli; extra == "brotli" in /src/venv/lib/python3.6/site-packages (from whitenoise[brotli]==4.1.2->-r /src/app/tools/../../app/requirements.txt (line 43)) (1.0.7)
backend_1   | Requirement already satisfied: jinja2 in /src/venv/lib/python3.6/site-packages (from coreschema>=0.0.4->drf-yasg==1.17.1->-r /src/app/tools/../../app/requirements.txt (line 20)) (2.11.2)
backend_1   | Requirement already satisfied: pyparsing>=2.0.2 in /src/venv/lib/python3.6/site-packages (from packaging->drf-yasg==1.17.1->-r /src/app/tools/../../app/requirements.txt (line 20)) (2.4.7)
backend_1   | Requirement already satisfied: itypes in /src/venv/lib/python3.6/site-packages (from coreapi>=2.3.3->drf-yasg==1.17.1->-r /src/app/tools/../../app/requirements.txt (line 20)) (1.2.0)
backend_1   | Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" in /src/venv/lib/python3.6/site-packages (from ruamel.yaml>=0.15.34->drf-yasg==1.17.1->-r /src/app/tools/../../app/requirements.txt (line 20)) (0.2.0)
backend_1   | Requirement already satisfied: jdcal in /src/venv/lib/python3.6/site-packages (from openpyxl<2.6.0,>=2.5.0->pyexcel-xlsx==0.5.7->-r /src/app/tools/../../app/requirements.txt (line 31)) (1.4.1)
backend_1   | Requirement already satisfied: et_xmlfile in /src/venv/lib/python3.6/site-packages (from openpyxl<2.6.0,>=2.5.0->pyexcel-xlsx==0.5.7->-r /src/app/tools/../../app/requirements.txt (line 31)) (1.0.1)
backend_1   | Requirement already satisfied: cffi!=1.11.3,>=1.8 in /src/venv/lib/python3.6/site-packages (from cryptography>=2.1.1; extra == "azuread"->social-auth-core[azuread]==3.0.0->-r /src/app/tools/../../app/requirements.txt (line 38)) (1.13.2)
backend_1   | Requirement already satisfied: multidict>=4.0 in /src/venv/lib/python3.6/site-packages (from yarl; python_version >= "3.4"->vcrpy==2.0.1->-r /src/app/tools/../../app/requirements.txt (line 41)) (4.7.4)
backend_1   | Requirement already satisfied: MarkupSafe>=0.23 in /src/venv/lib/python3.6/site-packages (from jinja2->coreschema>=0.0.4->drf-yasg==1.17.1->-r /src/app/tools/../../app/requirements.txt (line 20)) (1.1.1)
backend_1   | Requirement already satisfied: pycparser in /src/venv/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.1.1; extra == "azuread"->social-auth-core[azuread]==3.0.0->-r /src/app/tools/../../app/requirements.txt (line 38)) (2.19)
backend_1   | ERROR: django-pyodbc-azure 2.1.0.0 has requirement Django<2.2,>=2.1.0, but you'll have django 2.2.10 which is incompatible.
backend_1   | Installing collected packages: Django
backend_1   |   Attempting uninstall: Django
backend_1   |     Found existing installation: Django 2.2.13
backend_1   |     Uninstalling Django-2.2.13:
backend_1   |       Successfully uninstalled Django-2.2.13
backend_1   | Successfully installed Django-2.2.10
backend_1   | WARNING: You are using pip version 20.0.1; however, version 20.1.1 is available.
backend_1   | You should consider upgrading via the '/src/venv/bin/python3 -m pip install --upgrade pip' command.
backend_1   | Initializing database
backend_1   | Operations to perform:
backend_1   |   Apply all migrations: admin, api, auth, authtoken, contenttypes, sessions, social_django
backend_1   | Running migrations:
backend_1   |   No migrations to apply.
backend_1   |   Your models have changes that are not yet reflected in a migration, and so won't be applied.
backend_1   |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
backend_1   | CommandError: Error: That username is already taken.
backend_1   | Starting django
backend_1   | Watching for file changes with StatReloader
```

**Comment by Hironsan** [comment]
Hi @David192 

I tried `docker-compose -f docker-compose.dev.yml up` command in the following environments. But I can't reproduce the error.

- Mac OS Mojave
  - docker-compose version 1.25.5, build 8a1c60f6
  - Docker version 19.03.8, build afacb8b
- Chromium OS 10.0_pre377782_p20200113-r10 clang version 10.0.0
  - docker-compose version 1.24.0, build 0aa59064
  - Docker version 19.03.11, build 42e35e61f3

If you give us more information about your environment like OS, Docker, docker-compose, doccano version and so on, it will help us to solve the problem.

In addition, the following page may be useful for you. Please try it.

- [I want to update to the latest doccano image](https://doccano.github.io/doccano/faq/#i-want-to-update-to-the-latest-doccano-image)

**Comment by Hironsan** [comment]
Please try the following:

- [I want to update to the latest doccano image](https://github.com/doccano/doccano/blob/master/docs/faq.md#i-want-to-update-to-the-latest-doccano-image)

**Comment by telpirion** [comment]
I also ran into this problem but was able to work around it.

# System information

* MacOS Catalina, 10.15.7
* Python 3
* Node 12.13.0
* Docker 19.03.13
* doccano commit #25d6ded

# Steps

1) Stop all processes and delete them. (Otherwise I kept getting a `volume is in use` error.)

        docker stop $(docker ps -aq)
        docker rm $(docker ps -aq)
 
1) Remove the doccano volumes per [here](https://doccano.github.io/doccano/faq/#i-want-to-update-to-the-latest-doccano-image).

        docker volume rm doccano_node_modules doccano_static_volume doccano_venv doccano_www

1) Restart doccano (dev).

        docker-compose -f docker-compose.dev.yml build --no-cache

# Observations

* I had just installed Docker onto this machine when I ran doccano for the first time. I started the local Docker tutorial (and had those projects floating around in my environment).
* I successfully ran doccano Prod before trying to run doccano Dev.
