### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by lucie-bau** [doccano/doccano#969]
How to reproduce the problem
---------
While installing doccano by following the instructions I always get bach the same error, none of the solutions I found helped.

```bash
docker-compose -f docker-compose.prod.yml up
Building backend
Step 1/7 : FROM alpine:3.9.6
 ---> 78a2ce922f86
Step 2/7 : CMD ["python3"]
 ---> Using cache
 ---> 8d798c10a660
Step 3/7 : WORKDIR /app
 ---> Using cache
 ---> 635331406aa6
Step 4/7 : ENV PYTHONDONTWRITEBYTECODE 1
 ---> Using cache
 ---> 8e3792bb0141
Step 5/7 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> 2db5cdc120a7
Step 6/7 : COPY . /app/
 ---> Using cache
 ---> e28262603dfe
Step 7/7 : RUN apk add -U --no-cache bash python3 python3-dev libpq postgresql-dev unixodbc-dev musl-dev g++ libffi-dev   && pip3 install --upgrade --no-cache-dir pip setuptools   && pip3 install --no-cache-dir -r requirements.txt   && ln -s /usr/bin/python3 /usr/bin/python   && apk del --no-cache python3-dev postgresql-dev unixodbc-dev musl-dev g++ libffi-dev
 ---> Running in 93c7bca07df6
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/38) Installing ncurses-terminfo-base (6.1_p20190105-r0)
(2/38) Installing ncurses-terminfo (6.1_p20190105-r0)
(3/38) Installing ncurses-libs (6.1_p20190105-r0)
(4/38) Installing readline (7.0.003-r1)
(5/38) Installing bash (4.4.19-r1)
Executing bash-4.4.19-r1.post-install
(6/38) Installing libgcc (8.3.0-r0)
(7/38) Installing libstdc++ (8.3.0-r0)
(8/38) Installing binutils (2.31.1-r2)
(9/38) Installing gmp (6.1.2-r1)
(10/38) Installing isl (0.18-r0)
(11/38) Installing libgomp (8.3.0-r0)
(12/38) Installing libatomic (8.3.0-r0)
(13/38) Installing mpfr3 (3.1.5-r1)
(14/38) Installing mpc1 (1.0.3-r1)
(15/38) Installing gcc (8.3.0-r0)
(16/38) Installing musl-dev (1.1.20-r5)
(17/38) Installing libc-dev (0.7.1-r0)
(18/38) Installing g++ (8.3.0-r0)
(19/38) Installing linux-headers (4.18.13-r1)
(20/38) Installing libffi (3.2.1-r6)
(21/38) Installing pkgconf (1.6.0-r0)
(22/38) Installing libffi-dev (3.2.1-r6)
(23/38) Installing db (5.3.28-r1)
(24/38) Installing libsasl (2.1.27-r2)
(25/38) Installing libldap (2.4.48-r1)
(26/38) Installing libpq (11.7-r0)
(27/38) Installing openssl-dev (1.1.1g-r0)
(28/38) Installing postgresql-libs (11.7-r0)
(29/38) Installing postgresql-dev (11.7-r0)
(30/38) Installing libbz2 (1.0.6-r7)
(31/38) Installing expat (2.2.8-r0)
(32/38) Installing gdbm (1.13-r1)
(33/38) Installing xz-libs (5.2.4-r0)
(34/38) Installing sqlite-libs (3.28.0-r3)
(35/38) Installing python3 (3.6.9-r3)
(36/38) Installing python3-dev (3.6.9-r3)
(37/38) Installing unixodbc (2.3.7-r0)
(38/38) Installing unixodbc-dev (2.3.7-r0)
Executing busybox-1.29.3-r10.trigger
OK: 296 MiB in 52 packages
Collecting pip
  Downloading https://files.pythonhosted.org/packages/5a/4a/39400ff9b36e719bdf8f31c99fe1fa7842a42fa77432e584f707a5080063/pip-20.2.2-py2.py3-none-any.whl (1.5MB)
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/b0/8b/379494d7dbd3854aa7b85b216cb0af54edcb7fce7d086ba3e35522a713cf/setuptools-50.0.0-py3-none-any.whl (783kB)
Installing collected packages: pip, setuptools
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
  Found existing installation: setuptools 40.6.2
    Uninstalling setuptools-40.6.2:
      Successfully uninstalled setuptools-40.6.2
Successfully installed pip-20.2.2 setuptools-50.0.0
Collecting apache-libcloud==2.4.0
  Downloading apache_libcloud-2.4.0-py2.py3-none-any.whl (2.9 MB)
Collecting applicationinsights==0.11.7
  Downloading applicationinsights-0.11.7-py2.py3-none-any.whl (56 kB)
Collecting colour==0.1.5
  Downloading colour-0.1.5-py2.py3-none-any.whl (23 kB)
Collecting chardet==3.0.4
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting coverage==4.5.3
  Downloading coverage-4.5.3.tar.gz (384 kB)
Collecting dj-database-url==0.5.0
  Downloading dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
Collecting Django==2.2.13
  Downloading Django-2.2.13-py3-none-any.whl (7.5 MB)
Collecting django-cloud-browser==0.5.0
  Downloading django-cloud-browser-0.5.0.tar.gz (52 kB)
Collecting django-cors-headers==3.1.1
  Downloading django_cors_headers-3.1.1-py3-none-any.whl (14 kB)
Collecting django-filter==2.0.0
  Downloading django_filter-2.0.0-py3-none-any.whl (69 kB)
Collecting django-heroku==0.3.1
  Downloading django_heroku-0.3.1-py2.py3-none-any.whl (6.2 kB)
Collecting django-mssql-backend==2.8.1
  Downloading django_mssql_backend-2.8.1-py3-none-any.whl (52 kB)
Collecting django-webpack-loader==0.6.0
  Downloading django_webpack_loader-0.6.0-py2.py3-none-any.whl (17 kB)
Collecting django-widget-tweaks==1.4.2
  Downloading django_widget_tweaks-1.4.2-py2.py3-none-any.whl (13 kB)
Collecting django-polymorphic==2.0.3
  Downloading django_polymorphic-2.0.3-py2.py3-none-any.whl (74 kB)
Collecting django-rest-polymorphic==0.1.8
  Downloading django_rest_polymorphic-0.1.8-py2.py3-none-any.whl (5.9 kB)
Collecting djangorestframework==3.10
  Downloading djangorestframework-3.10.0-py3-none-any.whl (908 kB)
Collecting djangorestframework-csv==2.1.0
  Downloading djangorestframework-csv-2.1.0.tar.gz (9.8 kB)
Collecting djangorestframework-filters==0.10.2
  Downloading djangorestframework_filters-0.10.2-py2.py3-none-any.whl (18 kB)
Collecting drf-yasg==1.17.1
  Downloading drf_yasg-1.17.1-py2.py3-none-any.whl (1.1 MB)
Collecting environs==4.1.0
  Downloading environs-4.1.0-py2.py3-none-any.whl (8.7 kB)
Collecting djangorestframework-xml==1.4.0
  Downloading djangorestframework_xml-1.4.0-py2.py3-none-any.whl (4.6 kB)
Collecting Faker==0.9.1
  Downloading Faker-0.9.1-py2.py3-none-any.whl (761 kB)
Collecting flake8==3.6.0
  Downloading flake8-3.6.0-py2.py3-none-any.whl (68 kB)
Collecting furl==2.0.0
  Downloading furl-2.0.0-py2.py3-none-any.whl (19 kB)
Collecting gunicorn==19.9.0
  Downloading gunicorn-19.9.0-py2.py3-none-any.whl (112 kB)
Collecting lockfile==0.12.2
  Downloading lockfile-0.12.2-py2.py3-none-any.whl (13 kB)
Collecting model-mommy==1.6.0
  Downloading model_mommy-1.6.0-py2.py3-none-any.whl (17 kB)
Collecting psycopg2-binary==2.7.7
  Downloading psycopg2-binary-2.7.7.tar.gz (428 kB)
Collecting pyexcel==0.5.14
  Downloading pyexcel-0.5.14-py2.py3-none-any.whl (82 kB)
Collecting pyexcel-xlsx==0.5.7
  Downloading pyexcel_xlsx-0.5.7-py2.py3-none-any.whl (9.7 kB)
Collecting python-dateutil==2.7.3
  Downloading python_dateutil-2.7.3-py2.py3-none-any.whl (211 kB)
Collecting pytz==2018.4
  Downloading pytz-2018.4-py2.py3-none-any.whl (510 kB)
Collecting requests==2.21.0
  Downloading requests-2.21.0-py2.py3-none-any.whl (57 kB)
Collecting six==1.11.0
  Downloading six-1.11.0-py2.py3-none-any.whl (10 kB)
Collecting seqeval==0.0.6
  Downloading seqeval-0.0.6-py3-none-any.whl (6.0 kB)
Collecting social-auth-app-django==4.0.0
  Downloading social_auth_app_django-4.0.0-py3-none-any.whl (24 kB)
Collecting social-auth-core[azuread,openidconnect]==3.3.3
  Downloading social_auth_core-3.3.3-py3-none-any.whl (326 kB)
Collecting text-unidecode==1.2
  Downloading text_unidecode-1.2-py2.py3-none-any.whl (77 kB)
Collecting unittest-xml-reporting==2.5.1
  Downloading unittest_xml_reporting-2.5.1-py2.py3-none-any.whl (19 kB)
Collecting vcrpy==2.0.1
  Downloading vcrpy-2.0.1-py2.py3-none-any.whl (33 kB)
Collecting vcrpy-unittest==0.1.7
  Downloading vcrpy_unittest-0.1.7-py2.py3-none-any.whl (6.8 kB)
Collecting whitenoise[brotli]==4.1.2
  Downloading whitenoise-4.1.2-py2.py3-none-any.whl (19 kB)
Collecting conllu==1.3.2
  Downloading conllu-1.3.2-py2.py3-none-any.whl (9.3 kB)
Collecting sqlparse
  Downloading sqlparse-0.3.1-py2.py3-none-any.whl (40 kB)
Collecting psycopg2
  Downloading psycopg2-2.8.5.tar.gz (380 kB)
Collecting pyodbc>=3.0
  Downloading pyodbc-4.0.30.tar.gz (266 kB)
Collecting unicodecsv
  Downloading unicodecsv-0.14.1.tar.gz (10 kB)
Collecting inflection>=0.3.1
  Downloading inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
Collecting ruamel.yaml>=0.15.34
  Downloading ruamel.yaml-0.16.10-py2.py3-none-any.whl (111 kB)
Collecting coreschema>=0.0.4
  Downloading coreschema-0.0.4.tar.gz (10 kB)
Collecting uritemplate>=3.0.0
  Downloading uritemplate-3.0.1-py2.py3-none-any.whl (15 kB)
Collecting packaging
  Downloading packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting coreapi>=2.3.3
  Downloading coreapi-2.3.3-py2.py3-none-any.whl (25 kB)
Collecting marshmallow>=2.7.0
  Downloading marshmallow-3.7.1-py2.py3-none-any.whl (45 kB)
Collecting python-dotenv
  Downloading python_dotenv-0.14.0-py2.py3-none-any.whl (17 kB)
Collecting defusedxml>=0.3
  Downloading defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: setuptools>=30 in /usr/lib/python3.6/site-packages (from flake8==3.6.0->-r requirements.txt (line 24)) (50.0.0)
Collecting mccabe<0.7.0,>=0.6.0
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting pycodestyle<2.5.0,>=2.4.0
  Downloading pycodestyle-2.4.0-py2.py3-none-any.whl (62 kB)
Collecting pyflakes<2.1.0,>=2.0.0
  Downloading pyflakes-2.0.0-py2.py3-none-any.whl (53 kB)
Collecting orderedmultidict>=1.0
  Downloading orderedmultidict-1.0.1-py2.py3-none-any.whl (11 kB)
Collecting texttable>=0.8.2
  Downloading texttable-1.6.2-py2.py3-none-any.whl (10 kB)
Collecting lml>=0.0.4
  Downloading lml-0.0.9-py2.py3-none-any.whl (9.9 kB)
Collecting pyexcel-io>=0.5.18
  Downloading pyexcel_io-0.5.20-py2.py3-none-any.whl (39 kB)
Collecting openpyxl<2.6.0,>=2.5.0
  Downloading openpyxl-2.5.14.tar.gz (173 kB)
Collecting urllib3<1.25,>=1.21.1
  Downloading urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
Collecting idna<2.9,>=2.5
  Downloading idna-2.8-py2.py3-none-any.whl (58 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting numpy>=1.14.0
  Downloading numpy-1.19.1.zip (7.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting PyJWT>=1.4.0
  Downloading PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
Collecting python3-openid>=3.0.10; python_version >= "3.0"
  Downloading python3_openid-3.2.0-py3-none-any.whl (133 kB)
Collecting oauthlib>=1.0.3
  Downloading oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Collecting requests-oauthlib>=0.6.1
  Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting cryptography>=1.4
  Downloading cryptography-3.1.tar.gz (534 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting python-jose>=3.0.0; extra == "openidconnect"
  Downloading python_jose-3.2.0-py2.py3-none-any.whl (26 kB)
Collecting yarl; python_version >= "3.4"
  Downloading yarl-1.5.1.tar.gz (173 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting wrapt
  Downloading wrapt-1.12.1.tar.gz (27 kB)
Collecting PyYAML
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
Collecting Brotli; extra == "brotli"
  Downloading Brotli-1.0.9.zip (510 kB)
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9"
  Downloading ruamel.yaml.clib-0.2.0.tar.gz (178 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cshu60wo/ruamel-yaml-clib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cshu60wo/ruamel-yaml-clib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ldak77_3
         cwd: /tmp/pip-install-cshu60wo/ruamel-yaml-clib/
    Complete output (21 lines):
    /usr/lib/python3.6/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
      warnings.warn("Setuptools is replacing distutils.")
    sys.argv ['/tmp/pip-install-cshu60wo/ruamel-yaml-clib/setup.py', 'egg_info', '--egg-base', '/tmp/pip-pip-egg-info-ldak77_3']
    test compiling test_ruamel_yaml
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cshu60wo/ruamel-yaml-clib/setup.py", line 960, in <module>
        main()
      File "/tmp/pip-install-cshu60wo/ruamel-yaml-clib/setup.py", line 957, in main
        setup(**kw)
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/site-packages/setuptools/_distutils/core.py", line 134, in setup
        ok = dist.parse_command_line()
      File "/usr/lib/python3.6/site-packages/setuptools/_distutils/dist.py", line 484, in parse_command_line
        args = self._parse_command_opts(parser, args)
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 903, in _parse_command_opts
        nargs = _Distribution._parse_command_opts(self, parser, args)
      File "/usr/lib/python3.6/site-packages/setuptools/_distutils/dist.py", line 548, in _parse_command_opts
        "command class %s must subclass Command" % cmd_class)
    distutils.errors.DistutilsClassError: command class <class 'setuptools.command.egg_info.egg_info'> must subclass Command
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Service 'backend' failed to build: The command '/bin/sh -c apk add -U --no-cache bash python3 python3-dev libpq postgresql-dev unixodbc-dev musl-dev g++ libffi-dev   && pip3 install --upgrade --no-cache-dir pip setuptools   && pip3 install --no-cache-dir -r requirements.txt   && ln -s /usr/bin/python3 /usr/bin/python   && apk del --no-cache python3-dev postgresql-dev unixodbc-dev musl-dev g++ libffi-dev' returned a non-zero code: 1
```

Your Environment
---------
*   Operating System: Windows 10
*   Python Version Used: 3.8.2

**Comment by pranavpawar3** [comment]
Facing exactly the same issue, been struggling to solve this for hours, but nothing worked. Would be great if somebody could guide to a fix.

* OS - Ubuntu 16.04
* Python - 3.7.3

Thanks.

**Comment by aaitken-apixio** [comment]
This appears to be related to the new release of setuptools version 50.0.0. If you force it to install an older version it will correctly compile. To do so edit the Dockerfile under the app folder and replace the last line with something like the following:

RUN apk add -U --no-cache bash python3 python3-dev libpq postgresql-dev unixodbc-dev musl-dev g++ libffi-dev \
  && pip3 install --upgrade --no-cache-dir pip setuptools==49.6.0 \
  && pip3 install --no-cache-dir -r requirements.txt \
  && ln -s /usr/bin/python3 /usr/bin/python \
  && apk del --no-cache python3-dev postgresql-dev unixodbc-dev musl-dev g++ libffi-dev

**Comment by kuraga** [comment]
Facing the same issue.

**Comment by lucie-bau** [comment]
> This appears to be related to the new release of setuptools version 50.0.0. If you force it to install an older version it will correctly compile. To do so edit the Dockerfile under the app folder and replace the last line with something like the following:
> 
> RUN apk add -U --no-cache bash python3 python3-dev libpq postgresql-dev unixodbc-dev musl-dev g++ libffi-dev
> && pip3 install --upgrade --no-cache-dir pip setuptools==49.6.0
> && pip3 install --no-cache-dir -r requirements.txt
> && ln -s /usr/bin/python3 /usr/bin/python
> && apk del --no-cache python3-dev postgresql-dev unixodbc-dev musl-dev g++ libffi-dev

Thank you! This solution worked.

**Comment by Hironsan** [comment]
It seems to me that this problem was fixed by the recent update of [ruamel.yaml.clib 0.2.2](https://pypi.org/project/ruamel.yaml.clib/0.2.2/). But I think pinning the versions of dependencies is a good practice for reproducibility. We will update Dockerfile and replace requirements.txt with Pipfile.lock.

**Comment by michaelsheidaei** [comment]
where the Dockerfile and is it under windowsapps?

**Comment by pavantanniru** [comment]
facing the same issue

**Comment by Saniyapathan** [comment]
facing same issue
